### ISSUE TITLE
Index rotation by message count not working on ES 7.11.0

### ISSUE THREAD

**Issue by BlueTeamNinja** [Graylog2/graylog2-server#10085]
Rotating Indexes by size or time works fine, but message count does not rotate the active write index when using Elasticsearch 7.11

## Expected Behavior

Active index to rotate after N messages

## Current Behavior
Active index does not rotate after N is reached.

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
1.  Upgrade ES to 7.11 (I used Docker) 
2. Set an index to Rotate after 100 messages or whatever will trigger
3. Populate index over the used message count

## Context
A lot of retention policies are built around this feature set.  While index count isn't necessarily a hard retention policy, it may be for archival / performance reasons. 

## Your Environment
Docker - standard compose file from website

* Graylog Version: 4.02-1 Enterprise
* Java Version: (whatever is in the container)
* Elasticsearch Version:  7.11.0
* MongoDB Version: Latest ??
* Operating System: ..
* Browser version: ..

**Comment by bernd** [comment]
@BlueTeamNinja We are currently not supporting Elasticsearch 7.11. Stay tuned for updates on this.

**Comment by KKeXX** [comment]
@bernd We saw the same error with ES 7.10.2 and Graylog 4.0.2
A manual rotate was/is possible

**Comment by bernd** [comment]
@KKeXX This has been fixed in https://github.com/Graylog2/graylog2-server/pull/10092 and will be part of the upcoming 4.0.3 release. Thanks for the update!

**Comment by KKeXX** [comment]
@bernd thanks for the update. Fix sounds good!
But I tink you mean 4.0.4? Cause I just upgraded to 4.0.3 and the problem persists (with EL 7.11) And #10092 has milestone set to 4.0.4.

**Comment by jalogisch** [comment]
we have in addition upgrade the docs to be specific about the versions:

https://github.com/Graylog2/documentation/pull/1079

**Comment by bernd** [comment]
@KKeXX Yeah, it didn't make it into 4.0.3 and will be part of the upcoming 4.0.4 release.
