### ISSUE TITLE
Reports generation failing (again) behind a reverse proxy

### ISSUE THREAD

**Issue by euidzero** [Graylog2/graylog2-server#11960]
Maybe issue [#10267](https://github.com/Graylog2/graylog2-server/issues/10267) is not completely fixed :

I'm using graylog 4.2.5 and my config looks like :

http_external_uri = https://mydomain.com/graylog
http_publish_uri = http://10.0.0.2:9000/

The following setup is used :
graylog server on 10.0.0.2:9000 -> http  reverse-proxy -> CDN (resolves for mydomain.com and does the SSL)

When generating report the chrome_debug.log  in Headless/report/Default shows that the resources are fetched from

http://10.0.0.2:9000/graylog/ instead of http://10.0.0.2:9000/.

Of course this fails as the server sends the  graylog "homepage" instead of the actual resource:

### expected behavior
the chrome report generation plugin should fetch : http://10.0.0.2:9000/config.js

### actual behavior
it fetches http://10.0.0.2:9000/graylog/config.js and reveive the content of the homepage (http://10.0.0.2:9000/)

Same if I do not set http_publish_uri.

### Your Environment
graylog server on 10.0.0.2:9000 -> http  reverse-proxy -> CDN (resolves for mydomain.com and does the SSL)

* Graylog Version: 4.2.1
* Java Version: openjdk-17-jre-headless
* Elasticsearch Version: 7.10.2
* MongoDB Version:  4.0.27
* Operating System: Ubuntu 20.04

**Comment by dennisoelkers** [comment]
Hey @euidzero:

can you try setting `report_render_uri = http://10.0.0.2:9000/`? That should fix it for your environment.

**Comment by euidzero** [comment]
Does not fix the issue for me. Exact same behavior and logs.

**Comment by dennisoelkers** [comment]
Ah, I see. The correct way to set it up for your environment would be:

  - remove the `http_external_uri` setting from your config
  - configure your proxy to send a `X-Graylog-Server-URL` header containing `https://mydomain.com/graylog`

Afaics, that should do it, please get back if it does not.

**Comment by dennisoelkers** [comment]
Hey @euidzero, did this fix it for you?

**Comment by euidzero** [comment]
This will be tested in 2 days max (production constraints ...).
THX

**Comment by euidzero** [comment]
The proposed changed fix the issue.

Thanks a lot.

**Comment by bernd** [comment]
@euidzero Thanks for the update! I am glad it works now! :+1: 

Pinging @dulanism for documentation. :slightly_smiling_face:
