### ISSUE TITLE
Datanode - received fatal alert: certificate_unknown

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#15057]
Sometimes, during the usual Datanode setup, the Opensearch process reports following error:

```
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - [2023-03-27T16:30:33,570][WARN ][o.o.t.TcpTransport       ] [node1] exception caught on transport layer [Netty4TcpChannel{localAddress=/[0:0:0:0:0:0:0:1]:9300, remoteAddress=/[0:0:0:0:0:0:0:1]:42522}], closing connection
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,575 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at java.lang.Thread.run(Thread.java:833) [?:?]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:358) ~[?:?]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293) ~[?:?]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:204) ~[?:?]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736) ~[?:?]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691) ~[?:?]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506) ~[?:?]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482) ~[?:?]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679) ~[?:?]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:296) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1343) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,576 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	... 16 more
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - [2023-03-27T16:30:33,571][WARN ][o.o.t.TcpTransport       ] [node1] exception caught on transport layer [Netty4TcpChannel{localAddress=/[0:0:0:0:0:0:0:1]:42522, remoteAddress=ip6-localhost/[0:0:0:0:0:0:0:1]:9300}], closing connection
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: No name matching ip6-localhost found
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.84.Final.jar:4.1.84.Final]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at java.lang.Thread.run(Thread.java:833) [?:?]
2023-03-27 16:30:33,577 INFO : org.graylog.datanode.management.OpensearchProcessImpl - Caused by: javax.net.ssl.SSLHandshakeException: No name matching ip6-localhost found
2023-03-27 16:30:33,578 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
2023-03-27 16:30:33,578 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:371) ~[?:?]
2023-03-27 16:30:33,578 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:314) ~[?:?]
2023-03-27 16:30:33,578 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:309) ~[?:?]

```

It has probably something to do with the dual IPv4/IPv6 stack setup of the machine. This error is described in https://opensearch.org/docs/latest/troubleshoot/tls/ 

## Current Behavior
The exception is logged but the node is responding fine. Maybe it will cause troubles in a secured multi-node cluster configuration?  

## Possible Solution

I think we have to either properly generate the transport certificate or instruct the Opensearch process to use correct IP or hostname.

## Steps to Reproduce (for bugs)
Generate a set of certificates for the datanode, using our certutil tool. Both transport and http sets should be generated. Configure these in the datanode.conf file (paths + passwords). Start the datanode and observe logs.

**Comment by janheise** [comment]
fixed with #17022

**Comment by mmangione** [comment]
@janheise - This issue is still present with a default installation and no options for Graylog & Datanode 6.3.1. I am running into it now.

**Comment by todvora** [comment]
@mmangione Can you tell me more about your issue? Do you have some stacktraces, configuration snippets or anything that would help me to debug your problem? Thanks!
