### ISSUE TITLE
Create/Update&close rule in source editor shows warning dialog

### ISSUE THREAD

**Issue by moesterheld** [Graylog2/graylog2-server#19008]
## Expected Behavior
No warning dialog is shown

## Current Behavior
When creating a new rule using the source code editor or clicking "Update and close" the following dialog is shown, which is wrong
![image](https://github.com/Graylog2/graylog2-server/assets/33032967/c5ffdc3f-bf12-4398-89ab-73a2610e99af)
The rule is saved whatever is clicked, however the editor is only closed when clicking "OK"

## Steps to Reproduce (for bugs)
1. Create a new rule in the source editor, click "Create rule"
2. Dialog is shown, click ok to go to the rules list
3. Edit generated rule
4. Click "Update & Close"
5. Dialog is shown once again

## Your Environment

* Graylog Version: 6.0.0.rc2
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by patrickmann** [comment]
Already fixed by Graylog2/graylog2-server#18880, but it wasn't backported to 6.0

**Comment by damianharouff** [comment]
This was noted in https://github.com/Graylog2/graylog2-server/issues/18718 and still present in rc.2. Are we going to release with this bug in place?

**Comment by patrickmann** [comment]
My bad - #18718 is marked `blocker`, so it needs to be backported to 6.0. I was confused because it had been set to status `done`. 
Adding the blocker label here too for good measure. I feel we could improve our process on tracking issues for backport.

**Comment by kmerz** [comment]
The PR is fixing for Event Definition. This needs another fix!

**Comment by zeeklop** [comment]
@kmerz @ousmaneo 
I wasn't able to reproduce the error locally running the latest code. Has this been resolved already?

**Comment by ousmaneo** [comment]
@zeeklop, I'm currently working on this. 
You can only reproduce it using a production build to run Graylog locally or on test environments.
