### ISSUE TITLE
Message table broken in Chrome when map widget is loaded

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#2147]
### Problem description

Adding the map widget to a search result in Chrome 50 leaves the message table in a weird state.
Basically the grid does not move down when the map widget gets added. Works fine in Firefox 45.0.2.

![screenshot from 2016-04-26 14 25 20](https://cloud.githubusercontent.com/assets/461/14818086/5eaf9a9e-0bbb-11e6-87ec-424004aa10e8.png)

### Steps to reproduce the problem

1. Execute search
2. Create quick values
3. Create map widget
4. See broken message table layout

### Environment

* Graylog Version: 2.0.0-rc.2-SNAPSHOT (2dcf46f)
* Operating System: Ubuntu 14.04 LTS
* Browser version: Chrome 50.0.2661.86 (64-bit)

**Comment by kroepke** [comment]
Looks fixed in newer chrome versions, please re-check.

**Comment by edmundoa** [comment]
I can still reproduce this in Chrome 50.0.2661.94 (64-bit), but as @kroepke mentioned, it seems fixed in newer Chrome versions (I checked the Canary channel).
I think we should leave this open until we see the fix in the Chrome stable release (or we find some time to look into it).

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
