### ISSUE TITLE
Stream alerts no longer firing after upgrade to 2.0

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#2169]
### Problem description
Stream alerts are no longer firing after upgrading to 2.0 even though the stream receives messages.

The Message count condition : 
Alert is triggered when there is more than one message in the last 3 minutes. Grace period: 0 minutes. Including last message in alert notification.

The above worked just fine in 1.3 but apparently no longer works in 2.0 - no alerts have been generated since upgrading.

There is a discrepancy between editing the existing message count condition and adding a new one which I cannot explain : 

<img width="1084" alt="screen shot 2016-05-02 at 11 11 33" src="https://cloud.githubusercontent.com/assets/1473308/14951105/e4f2c12c-1056-11e6-931e-5ec9b6d45209.png">

**Comment by henrikjohansen** [comment]
To clarify - adding a new message count condition says  "than 1 messages in the last 3 minute and " editing the existing one says "than 1 message in the last  3 messages and"  ...

**Comment by dennisoelkers** [comment]
Fixed the wording glitch. I am not able to reproduce non-firing stream alerts. Is the stream paused? Do you see new stream alerts being added to the list at the bottom of the "Manage Alerts" page?

**Comment by henrikjohansen** [comment]
No, streams is active and receiving messages. I just deleted & recreated the alert conditions and now alerts are firing again ... I had to do this for several streams ...

**Comment by dennisoelkers** [comment]
Do you have a backup of your MongoDB before you recreated the stream alert conditions? It would really help if you could extract one that is not working, so we can investigate what's causing this.

**Comment by henrikjohansen** [comment]
No - unfortunately not ....

**Comment by jothoma1** [comment]
Same for me after upgrading to 2.0 streams alerts didn't work. No mongodb backup...
i'll try to delete & recreate alert condition

**Comment by dennisoelkers** [comment]
Do you see anything in your server logs?

**Comment by milgner** [comment]
I'm also experiencing this issue. Is there anything specific you want from my MongoDB?
I already looked at `db.streams.find().pretty()` and `db.alarmcallbackconfigurations.find().pretty()` and they both look very reasonable.

**Comment by dennisoelkers** [comment]
This has been fixed and the fix will be included in 2.0.1. Thanks for helping, everybody!

**Comment by milgner** [comment]
Problem still persists after upgrading to 2.0.1. I tried re-creating the alert conditions for the streams but still no luck. Is there any script that needs to be run to get it working again?

I considered that it may be a problem with the notifier, but the "Triggered alerts" section on the stream configuration page also says "This stream has never triggered an alert." even though there are many messages in the stream that should have triggered the alert.

The current configuration is: `Alert is triggered when there are more than 3 messages in the last 5 minutes. Grace period: 15 minutes. Including last 3 messages in alert notification. `

Should I open a new issue?
