### ISSUE TITLE
Bad url generated in REST API browser

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2602]
### Problem description
API browser generates url to api-docs, and not to service itself.
![image](https://cloud.githubusercontent.com/assets/17475270/17368495/ec7a8f76-599c-11e6-8ec8-6680e562f9da.png)

### Environment
* Graylog Version: 2.1.0-beta2

**Comment by joschi** [comment]
@hc4 I suspect that's a direct consequence of setting `web_endpoint_uri` to an empty string.

Try to remove that setting or set it to a valid absolute URI.

**Comment by hc4** [comment]
I need it to be relative
I need all requests have the same host as for first web request.
Because external users will use fqdn to access server, and locals will use just http://graylog/

**Comment by hc4** [comment]
Just tested with `web_endpoint_uri = http://graylog/` and problem with API browser solved, but now I can access graylog only at [http://graylog/](http://graylog/), and not at [http://[ip]/](http://[ip]/) or http://graylog.domain.name/

**Comment by kroepke** [comment]
should be addressed by #2614

**Comment by bernd** [comment]
This should be fixed in 2.1.0-beta.4. Please re-open if this is still a problem. Thank you!

**Comment by hc4** [comment]
Not fixed
![image](https://cloud.githubusercontent.com/assets/17475270/17814772/ff51b800-6639-11e6-97f8-cb759dfb5250.png)

**Comment by hc4** [comment]
Graylog 2.1.0-beta.4+d6329d0, codename Smuttynose

**Comment by hc4** [comment]
Maybe problem caused by bad Base URI?
![image](https://cloud.githubusercontent.com/assets/17475270/17815912/13fa61f8-663f-11e6-977f-31c0dcfb3867.png)

swaggerUI.api have bth baseUri and rul set to api-docs.
![image](https://cloud.githubusercontent.com/assets/17475270/17815960/6a2ea520-663f-11e6-8fef-ce4f75ba10eb.png)

**Comment by hc4** [comment]
Sso plugin props
![image](https://cloud.githubusercontent.com/assets/17475270/17816013/a6c3dd16-663f-11e6-9aee-f2408f433e37.png)

If i change basepath for SwaggerResource to http://graylog, correct request generated:
![image](https://cloud.githubusercontent.com/assets/17475270/17816070/f24aa210-663f-11e6-9608-a0f5629f9545.png)
![image](https://cloud.githubusercontent.com/assets/17475270/17816074/fb18cde0-663f-11e6-80eb-22aaefa64f09.png)

**Comment by hc4** [comment]
Adding header X-graylog-server-url solves problem.
But it's only workaround.

**Comment by joschi** [comment]
I'm closing this issue because we're going to refactor the network listeners (web interface and Graylog REST API) in Graylog 2.2.x anyway.

Additionally, this bug (?) seems to be an edge case and a workaround using the `X-Graylog-Server-URL` request header exists.
