### ISSUE TITLE
LDAP Settings not showing up

### ISSUE THREAD

**Issue by Aguay-val** [Graylog2/graylog2-server#3167]
When i try to access to LDAP settings there is a "Loading Icon" with nothing else. Even after few seconds/minutes.

## Expected Behavior
I should be able to see all configurations settings like this : 

![http://docs.graylog.org/en/2.1/_images/ldap_settings.png](http://docs.graylog.org/en/2.1/_images/ldap_settings.png)

## Current Behavior
I can't see any LDAP settings.
![https://photo.baraise.info/uploads/big/dd6e952e828ec77c8764c467459bf764.png](https://photo.baraise.info/uploads/big/dd6e952e828ec77c8764c467459bf764.png)

I can see logs from the web console, obviously i changed the fqdn of my graylog server : 

```
Unhandled rejection TypeError: Cannot read property 'value' of null
    at https://graylog-server.domain.tld/assets/6.6.7c2b0dd11d39e6e4468c.js:24:11721
    at Array.map (native)
    at n.filterOptions (https://graylog-server.domain.tld/assets/6.6.7c2b0dd11d39e6e4468c.js:24:11697)
    at n.getStateFromValue (https://graylog-server.domain.tld/assets/6.6.7c2b0dd11d39e6e4468c.js:24:6072)
    at n.componentWillMount (https://graylog-server.domain.tld/assets/6.6.7c2b0dd11d39e6e4468c.js:24:4399)
    at p.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:34:3885)
    at p.i [as mountComponent] (https://graylog-server.domain.tld/assets/vendor.js:7:18665)
    at Object.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:7:31500)
    at p.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:34:4103)
    at p.i [as mountComponent] (https://graylog-server.domain.tld/assets/vendor.js:7:18665)
    at Object.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:7:31500)
    at p.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:34:4103)
    at p.i [as mountComponent] (https://graylog-server.domain.tld/assets/vendor.js:7:18665)
    at Object.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:7:31500)
    at v.mountChildren (https://graylog-server.domain.tld/assets/vendor.js:35:10872)
    at v._createContentMarkup (https://graylog-server.domain.tld/assets/vendor.js:34:20599)
    at v.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:34:19499)
    at Object.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:7:31500)
    at v.mountChildren (https://graylog-server.domain.tld/assets/vendor.js:35:10872)
    at v._createContentMarkup (https://graylog-server.domain.tld/assets/vendor.js:34:20599)
    at v.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:34:19499)
    at Object.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:7:31500)
    at p.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:34:4103)
    at p.i [as mountComponent] (https://graylog-server.domain.tld/assets/vendor.js:7:18665)
    at Object.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:7:31500)
    at p.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:34:4103)
    at p.i [as mountComponent] (https://graylog-server.domain.tld/assets/vendor.js:7:18665)
    at Object.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:7:31500)
    at v.mountChildren (https://graylog-server.domain.tld/assets/vendor.js:35:10872)
    at v._createContentMarkup (https://graylog-server.domain.tld/assets/vendor.js:34:20599)
    at v.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:34:19499)
    at Object.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:7:31500)
    at v.mountChildren (https://graylog-server.domain.tld/assets/vendor.js:35:10872)
    at v._createContentMarkup (https://graylog-server.domain.tld/assets/vendor.js:34:20599)
    at v.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:34:19499)
    at Object.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:7:31500)
    at v.mountChildren (https://graylog-server.domain.tld/assets/vendor.js:35:10872)
    at v._createContentMarkup (https://graylog-server.domain.tld/assets/vendor.js:34:20599)
    at v.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:34:19499)
    at Object.mountComponent (https://graylog-server.domain.tld/assets/vendor.js:7:31500)
```

## Steps to Reproduce 

1.Connect to graylog (with admin rights)
2. Go to System/authentication tabs
3. Click on Ldap/Active Directory 

## Context
I was wondering if i had correctly set up the ldap connection and wanted to add rights for a user account.
If i want to change to an other tab (for exemple search) i have to F5 the page.

## My Environment

* Graylog Version: 2.1.2+50e449a
* Elasticsearch Version: 2.4.2
* MongoDB Version: v2.4.10
* Operating System: debian jessie kernel 4.7.0.0
* Browser version: Opera/Chrome/Firefox (latest version)

**Comment by tubesenf** [comment]
Greetings,
we have the same Problem in our Env:
Version:   2.1.2+50e449a, codename Smuttynose
JVM:    PID 15581, Oracle Corporation 1.8.0_71 on Linux 2.6.32-642.3.1.el6.x86_64

Not sure if the error correspond with our Problem, no real ldap error found in server.log

> 2017-01-17T07:24:56.918+01:00 WARN  [ModularRealmAuthenticator] Realm [org.graylog2.security.realm.SessionAuthenticator@3fa1be22] threw an exception during a multi-realm authentication attempt:
> java.lang.NullPointerException
>         at org.graylog2.database.PersistedServiceImpl.collection(PersistedServiceImpl.java:113) ~[graylog.jar:?]
>         at org.graylog2.database.PersistedServiceImpl.destroy(PersistedServiceImpl.java:160) ~[graylog.jar:?]
>         at org.graylog2.security.MongoDbSessionDAO.doDelete(MongoDbSessionDAO.java:119) ~[graylog.jar:?]
>         at org.apache.shiro.session.mgt.eis.CachingSessionDAO.delete(CachingSessionDAO.java:304) ~[graylog.jar:?]
>         at org.apache.shiro.session.mgt.DefaultSessionManager.delete(DefaultSessionManager.java:240) ~[graylog.jar:?]
>         at org.apache.shiro.session.mgt.DefaultSessionManager.afterExpired(DefaultSessionManager.java:207) ~[graylog.jar:?]
>         at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.onExpiration(AbstractValidatingSessionManager.java:159) ~[graylog.jar:?]
>         at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.validate(AbstractValidatingSessionManager.java:145) ~[graylog.jar:?]
>         at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doGetSession(AbstractValidatingSessionManager.java:120) ~[graylog.jar:?]
>         at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupSession(AbstractNativeSessionManager.java:148) ~[graylog.jar:?]
>         at org.apache.shiro.session.mgt.AbstractNativeSessionManager.getSession(AbstractNativeSessionManager.java:140) ~[graylog.jar:?]
>         at org.apache.shiro.mgt.SessionsSecurityManager.getSession(SessionsSecurityManager.java:156) ~[graylog.jar:?]
>         at org.apache.shiro.mgt.DefaultSecurityManager.resolveContextSession(DefaultSecurityManager.java:456) ~[graylog.jar:?]
>         at org.apache.shiro.mgt.DefaultSecurityManager.resolveSession(DefaultSecurityManager.java:442) ~[graylog.jar:?]
>         at org.apache.shiro.mgt.DefaultSecurityManager.createSubject(DefaultSecurityManager.java:338) ~[graylog.jar:?]
>         at org.apache.shiro.subject.Subject$Builder.buildSubject(Subject.java:846) ~[graylog.jar:?]
>         at org.graylog2.security.realm.SessionAuthenticator.doGetAuthenticationInfo(SessionAuthenticator.java:57) ~[graylog.jar:?]
>         at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:568) ~[graylog.jar:?]
>         at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doMultiRealmAuthentication(ModularRealmAuthenticator.java:219) [graylog.jar:?]
>         at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:269) [graylog.jar:?]
>         at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198) [graylog.jar:?]
>         at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106) [graylog.jar:?]
>         at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270) [graylog.jar:?]
>         at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256) [graylog.jar:?]
>         at org.graylog2.shared.security.ShiroSecurityContext.loginSubject(ShiroSecurityContext.java:101) [graylog.jar:?]
>         at org.graylog2.shared.security.ShiroAuthenticationFilter.filter(ShiroAuthenticationFilter.java:48) [graylog.jar:?]
>         at org.graylog2.rest.resources.system.SessionsResource.validateSession(SessionsResource.java:183) [graylog.jar:?]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_71]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71]
>         at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
>         at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [graylog.jar:?]
>         at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [graylog.jar:?]
>         at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [graylog.jar:?]
>         at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [graylog.jar:?]
>         at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [graylog.jar:?]
>         at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [graylog.jar:?]
>         at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [graylog.jar:?]
>         at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [graylog.jar:?]
>         at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
>         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
>         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
>         at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
>         at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
>         at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
>         at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
>         at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
>         at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
>         at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
>         at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
>         at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71]
>         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
> 

R/Daniel

**Comment by joschi** [comment]
@tubesenf I think these are 2 different issues. Yours has already been resolved in #3335.

**Comment by joschi** [comment]
@Aguay-val Are there any error messages in the logs of your Graylog node?
Also, what's in the `ldap_settings` collection in MongoDB?

**Comment by Aguay-val** [comment]
@joschi  I can't find any ldap log in the logs of my Graylog Node.

Here the content of my `ldap_settings` : 

```
{
        "_id" : ObjectId("5783b6c19ad21d33fa49704e"),
        "use_start_tls" : false,
        "system_password" : "18ff63817451592c82fd86917bb06f1e2e83362fee2138f6afe5cc65aff85294",
        "principal_search_pattern" : "(&(objectClass=user)(sAMAccountName={0})(memberof=OU=PersonnalOU,DC=Subdomain,DC=DOMAIN,DC=TLD))",
        "username_attribute" : "displayName",
        "system_password_salt" : "************",
        "system_username" : "CN=Graylog,OU=PersonnalOU,DC=Subdomain,DC=DOMAIN,DC=TLD",
        "trust_all_certificates" : false,
        "group_search_base" : "OU=PersonnalOU,DC=Subdomain,DC=DOMAIN,DC=TLD",
        "default_group" : "5783b0e29ad21d1f32d3a803",
        "group_search_pattern" : "(objectClass=group)",
        "active_directory" : true,
        "enabled" : true,
        "additional_default_groups" : [
                "578517f69ad21d0373951742"
        ],
        "group_id_attribute" : "CN",
        "search_base" : "OU=PersonnalOU,DC=Subdomain,DC=DOMAIN,DC=TLD",
        "group_role_mapping_list" : [
                {
                        "role_id" : "582f109580ffce6209f32b0f",
                        "group" : "My Group"
                }
        ],
        "ldap_uri" : "ldap://my-server.tld:389/"
}
```

I obviously hide some sensitive information. If you see anything else sensitive, please hide them.

**Comment by dennisoelkers** [comment]
Could you please provide us with the output you get when do an authenticated GET as an admin to `http://$graylogapi/roles`?

**Comment by Aguay-val** [comment]
@dennisoelkers Here my get output : 

```
{
  "roles": [
    {
      "name": "Admin",
      "description": "Grants all permissions for Graylog administrators (built-in)",
      "permissions": [
        "*"
      ],
      "read_only": true
    },
    {
      "name": "MyCustomGroup",
      "description": "Custom group for admins users ",
      "permissions": [
        "streams:edit:5784e8d09ad21d49445f5e1e",
        "dashboards:read:5783c9499ad21d33fa49843a",
        "dashboards:read:5783c9499ad21d33fa49843b",
        "streams:read:5783c9499ad21d33fa498432",
        "dashboards:edit:57a06fe19ad21d20044af318",
        "dashboards:edit:5783c9499ad21d33fa498437",
        "dashboards:edit:5783c9499ad21d33fa498438",
        "dashboards:edit:5783c9499ad21d33fa498435",
        "dashboards:read:5784eea29ad21d49445f6440",
        "dashboards:edit:5783c9499ad21d33fa498439",
        "dashboards:edit:5784eea29ad21d49445f6440",
        "dashboards:read:57a06fe19ad21d20044af318",
        "streams:read:583407f180ffce6209f86518",
        "streams:read:57a2fa8f9ad21d20044d9e8d",
        "dashboards:edit:5783c9499ad21d33fa49843a",
        "dashboards:edit:5783c9499ad21d33fa49843b",
        "streams:edit:5783c9499ad21d33fa498432",
        "streams:read:5784e8d09ad21d49445f5e1e",
        "dashboards:read:5783c9499ad21d33fa498439",
        "streams:edit:57a2fa8f9ad21d20044d9e8d",
        "dashboards:read:5783c9499ad21d33fa498435",
        "dashboards:read:5783c9499ad21d33fa498437",
        "dashboards:read:5783c9499ad21d33fa498438"
      ],
      "read_only": false
    },
    {
      "name": "Reader",
      "description": "Grants basic permissions for every Graylog user (built-in)",
      "permissions": [
        "clusterconfigentry:read",
        "indexercluster:read",
        "messagecount:read",
        "journal:read",
        "inputs:read",
        "metrics:read",
        "savedsearches:edit",
        "fieldnames:read",
        "buffers:read",
        "system:read",
        "savedsearches:create",
        "jvmstats:read",
        "decorators:read",
        "throughput:read",
        "savedsearches:read",
        "messages:read"
      ],
      "read_only": true
    },
    {
      "name": "Reader-Monitoring",
      "description": "Grant Permission for Monitoring User Only.",
      "permissions": [
        "clusterconfigentry:read",
        "indexercluster:read",
        "streams:read",
        "messagecount:read",
        "journal:read",
        "inputs:read",
        "metrics:read",
        "savedsearches:edit",
        "fieldnames:read",
        "buffers:read",
        "system:read",
        "stream_outputs:read",
        "savedsearches:create",
        "jvmstats:read",
        "throughput:read",
        "savedsearches:read",
        "messages:read"
      ],
      "read_only": false
    }
  ],
  "total": 4
}
```

**Comment by tubesenf** [comment]
Hi,
we fixed our problem by deleting all content from ldap_settings. 
After a new configuration (same values) all is fine until now.
We had to remap all roles and ldap groups and think that the problem was caused by an mapping to a ldap group which no longer exists.
It would be nice to debug ldap mapping and auth errors but even with graylog server debug enabled we couldn't find any ldap specific messages.

R/Daniel

**Comment by Aguay-val** [comment]
Thanks @tubesenf !

what I did it's drop `ldap_settings`:

`db.ldap_settings.drop()`

I restart graylog server, try to log me in and i was able to modify ldap settings. 

Obviously they were empty.

Thanks for the tips !

**Comment by Aguay-val** [comment]
Something i noticed is when you make group mapping settings and you forgot `Group Name Attribute` when you try to go to `Ldap Group Mapping` there is a "Loading Icon" and nothing appear. 
No error, no failed just loading icon.

**Comment by Aguay-val** [comment]
Hi all,

There is something else strange. Thanks @tubesenf for his solution. But now, when i try to bind a user into "admin" role, few hours/

**Comment by Aguay-val** [comment]
Sorry miss click.

**Comment by mubeennakade** [comment]
@Aguay-val  Your solution of drop worked like a charm.. thanks

**Comment by mubeennakade** [comment]
@tubesenf Thanks for pointer

**Comment by bernd** [comment]
The LDAP configuration has been rewritten in the upcoming 4.0 release. Please open a new issue if you still see problems like this. Thank you!
