### ISSUE TITLE
2.2 Beta 4 - Alert and Stream tabs not working

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog2-server#3348]
We have upgraded to the beta4 release of 2.2 and the Alert and Stream tabs are not working - clicking on them does not load and data.

The UI also keeps reloading every few seconds I.e drops to the error page then reloads.

Rgds

**Comment by dennisoelkers** [comment]
What are the error messages of your browser's javascript console?

**Comment by bernd** [comment]
@urban-moniker Did you create alert conditions with the 2.2 beta release? If so, your database entries for the alert conditions use the wrong type. This was an issue we fixed in beta.4 but didn't create a migration to fix the broken data. That migration will be included in the next beta.

To be sure that this is the issue, please send us the javascript console output that @dennisoelkers asked for and the server log. Thank you!

**Comment by urban-moniker** [comment]
Hi - I attach two files - one for the Stream tab log and the other for the Alerts tab.

[Alert_Console_errors.txt](https://github.com/Graylog2/graylog2-server/files/708103/Alert_Console_errors.txt)
[Stream_Console_errors.txt](https://github.com/Graylog2/graylog2-server/files/708104/Stream_Console_errors.txt)

There are no entries in the server.log at the time of accessing the site.

Thanks - hope this is the right data.

Rgds

**Comment by edmundoa** [comment]
Hi @urban-moniker, could you please try accessing the alerts and streams pages after disabling the Threat Intelligence Plugin for Graylog? That is still not compatible with 2.2 and I think may be behind this issue.

**Comment by urban-moniker** [comment]
Hi, that looks to have fixed many of the issues - I can now access the Alerts and Streams pages.  Note that I had to remove the TIP jar file completely as just disabling the plugin features in the Config page did not work.

I am still having getting the constant page reloads (about every 10-15 seconds).  Each reload logs (or is caused by) the following entry in the debug console:-

_"plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.447cc1d1fae317a0dfe4.js:55:21724"_

with the following linked text:-

_"!function(t){e.exports=t()}(function(){var e,r,exports;return function e(t,n,i){function r(s,a){if(!n[s]){if(!t[s]){var l="function"==typeof _dereq_&&_dereq_;if(!a&&l)return l(s,!0);if(o)return o(s,!0);var u=new Error("Cannot find module '"+s+"'");throw u.code="MODULE_NOT_FOUND",u}var c=n[s]={exports:{}};t[s][0].call(c.exports,function(e){var n=t[s][1][e];return r(n?n:e)},c,c.exports,e,t,n,i)}return n[s].exports}for(var o="function"==typeof _dereq_&&_dereq_,s=0;s<i.length;s++)r(i[s]);return r}({1:[function(e,t,exports){"use strict";t.exports=function(e){function t(e){var t=new n(e),i=t.promise();return t.setHowMany(1),t.setUnwrap(),t.init(),i}var n=e._SomePromiseArray;e.any=function(e){return t(e)},e.prototype.any=function(){return t(this)}}},{}],2:[function(e,n,exports){"use strict";function i(){this._customScheduler=!1,this._isTickUsed=!1,this._lateQueue=new u(16),this._normalQueue=new u(16),this._haveDrainedQueues=!1,this._trampolineEnabled=!0;var e=this;this.drainQueues=function(){e._drainQueues()},this._schedule=l}function r(e,t,n){this._lateQueue.push(e,t,n),this._queueTick()}function o(e,t,n){this._normalQueue.push(e,t,n),this._queueTick()}function s(e){this._normalQueue._pushOne(e),this._queueTick()}var a;try{throw new Error}catch(e){a=e}var l=e("./schedule"),u=e("./queue"),c=e("./util");i.prototype.setScheduler=function(e){var t=this._schedule;return this._schedule=e,this._customScheduler=!0,t},i.prototype.hasCustomScheduler=function(){return this._customScheduler},i.prototype.enableTrampoline=function(){this._trampolineEnabled=!0},i.prototype.disableTrampolineIfNecessary=function(){c.hasDevTools&&(this._trampolineEnabled=!1)},i.prototype.haveItemsQueued=function(){return this._isTickUsed||this._haveDrainedQueues},i.prototype.fatalError=function(e,n){n?(t.stderr.write("Fatal "+(e instanceof Error?e.stack:e)+"\n"),t.exit(2)):this.throwLater(e)},i.prototype.throwLater=function(e,t){if(1===arguments.length&&(t=e,e=function(){throw t}),"undefined"!=typeof setTimeout)setTimeout(function(){e(t)},0);else try{this._schedule(function(){e(t)})}catch(e){throw new Error("No async scheduler available\n\n    See http://goo.gl/MqrFmX\n")}},c.hasDevTools?(i.prototype.invokeLater=function(e,t,n){this._trampolineEnabled?r.call(this,e,t,n):this._schedule(function(){setTimeout(function(){e.call(t,n)},100)})},i.prototype.invoke=function(e,t,n){this._trampolineEnabled?o.call(this,e,t,n):this._schedule(function(){e.call(t,n)})},i.prototype.settlePromises=function(e){this._trampolineEnabled?s.call(this,e):this._schedule(function(){e._settlePromises()})}):(i.prototype.invokeLater=r,i.prototype.invoke=o,i.prototype.settlePromises=s),i.prototype._drainQueue=function(e){for(;e.length()>0;){var t=e.shift();if("function"==typeof t){var n=e.shift(),i=e.shift();t.call(n,i)}else t._settlePromises()}},i.prototype._drainQueues=function(){this._drainQueue(this._normalQueue),this._reset(),this._haveDrainedQueues=!0,this._drainQueue(this._lateQueue)},i.prototype._queueTick=function(){this._isTickUsed||(this._isTickUsed=!0,this._schedule(this.drainQueues))},i.prototype._reset=function(){this._isTickUsed=!1},n.exports=i,n.exports.firstLineError=a},{"./queue":26,"./schedule":29,"./util":36}],3:[function(e,t,exports){"use strict";t.exports=function(e,t,n,i){var r=!1,o=function(e,t){this._reject(t)},s=function(e,t){t.promiseRejectionQueued=!0,t.bindingPromise._then(o,o,null,this,e)},a=function(e,t){0===(50397184&this._bitField)&&this._resolveCallback(t.target)},l=function(e,t){t.promiseRejectionQueued||this._reject(e)};e.prototype.bind=function(o){r||(r=!0,e.prototype._propagateFrom=i.propagateFromFunction(),e.prototype._boundValue=i.boundValueFunction());var u=n(o),c=new e(t);c._propagateFrom(this,1);var h=this._target();if(c._setBoundTo(u),u instanceof e){var d={promiseRejectionQueued:!1,promise:c,target:h,bindingPromise:u};h._then(t,s,void 0,c,d),u._then(a,l,void 0,c,d),c._setOnCancel(u)}else c._resolveCallback(h);return c},e.prototype._setBoundTo=function(e){void 0!==e?(this._bitField=2097152|this._bitField,this._boundTo=e):this._bitField=this._bitField&-2097153},e.prototype._isBound=function(){return 2097152===(2097152&this._bitField)},e.bind=function(t,n){return e.resolve(n).bind(t)}}},{}],4:[function(e,t,exports){"use strict";function n(){try{Promise===r&&(Promise=i)}catch(e){}return r}var i;"undefined"!=typeof Promise&&(i=Promise);var r=e("./promise")();r.noConflict=n,t.exports=r},{"./promise":22}],5:[function(e,t,exports){"use strict";var n=Object.create;if(n){var i=n(null),r=n(null);i[" size"]=r[" size"]=0}t.exports=function(t){function n(e,n){var i;if(null!=e&&(i=e[n]),"function"!=typeof i){var r="Object "+a.classString(e)+" has no method '"+a.toString(n)+"'";throw new t.TypeError(r)}return i}function i(e){var t=this.pop(),i=n(e,t);return i.apply(e,this)}function r(e){return e[this]}function o(e){var t=+this;return t<0&&(t=Math.max(0,t+e.length)),e[t]}var s,a=e("./util"),l=a.canEvaluate;a.isIdentifier;t.prototype.call=function(e){var t=[].slice.call(arguments,1);return t.push(e),this._then(i,void 0,void 0,t,void 0)},t.prototype.get=function(e){var t,n="number"==typeof e;if(n)t=o;else if(l){var i=s(e);t=null!==i?i:r}else t=r;return this._then(t,void 0,void 0,e,void 0)}}},{"./util":36}],6:[function(e,t,exports){"use strict";t.exports=function(t,n,i,r){var o=e("./util"),s=o.tryCatch,a=o.errorObj,l=t._async;t.prototype.break=t.prototype.cancel=function(){if(!r.cancellation())return this._warn("cancellation is disabled");for(var e=this,t=e;e._isCancellable();){if(!e._cancelBy(t)){t._isFollowing()?t._followee().cancel():t._cancelBranched();break}var n=e._cancellationParent;if(null==n||!n._isCancellable()){e._isFollowing()?e._followee().cancel():e._cancelBranched();break}e._isFollowing()&&e._followee().cancel(),e._setWillBeCancelled(),t=e,e=n}},t.prototype._branchHasCancelled=function(){this._branchesRemainingToCancel--},t.prototype._enoughBranchesHaveCancelled=function(){return void 0===this._branchesRemainingToCancel||this._branchesRemainingToCancel<=0},t.prototype._cancelBy=function(e){return e===this?(this._branchesRemainingToCancel=0,this._invokeOnCancel(),!0):(this._branchHasCancelled(),!!this._enoughBranchesHaveCancelled()&&(this._invokeOnCancel(),!0))},t.prototype._cancelBranched=function(){this._enoughBranchesHaveCancelled()&&this._cancel()},t.prototype._cancel=function(){this._isCancellable()&&(this._setCancelled(),l.invoke(this._cancelPromises,this,void 0))},t.prototype._cancelPromises=function(){this._length()>0&&this._settlePromises()},t.prototype._unsetOnCancel=function(){this._onCancelField=void 0},t.prototype._isCancellable=function(){return this.isPending()&&!this._isCancelled()},t.prototype.isCancellable=function(){return this.isPending()&&!this.isCancelled()},t.prototype._doInvokeOnCancel=function(e,t){if(o.isArray(e))for(var n=0;n<e.length;++n)this._doInvokeOnCancel(e[n],t);else if(void 0!==e)if("function"==typeof e){if(!t){var i=s(e).call(this._boundValue());i===a&&(this._attachExtraTrace(i.e),l.throwLater(i.e))}}else e._resultCancelled(this)},t.prototype._invokeOnCancel=function(){var e=this._onCancel();this._unsetOnCancel(),l.invoke(this._doInvokeOnCancel,this,e)},t.prototype._invokeInternalOnCancel=function(){this._isCancellable()&&(this._doInvokeOnCancel(this._onCancel(),!0),this._unsetOnCancel())},t.prototype._resultCancelled=function(){this.cancel()}}},{"./util":36}],7:[function(e,t,exports){"use strict";t.exports=function(t){function n(e,n,a){return function(l){var u=a._boundValue();e:for(var c=0;c<e.length;++c){var h=e[c];if(h===Error||null!=h&&h.prototype instanceof Error){if(l instanceof h)return o(n).call(u,l)}else if("function"==typeof h){var d=o(h).call(u,l);if(d===s)return d;if(d)return o(n).call(u,l)}else if(i.isObject(l)){for(var f=r(h),p=0;p<f.length;++p){var g=f[p];if(h[g]!=l[g])continue e}return o(n).call(u,l)}}return t}}var i=e("./util"),r=e("./es5").keys,o=i.tryCatch,s=i.errorObj;return n}},{"./es5":13,"./util":36}],8:[function(e,t,exports){"use strict";t.exports=function(e){function t(){this._trace=new t.CapturedTrace(i())}function n(){if(r)return new t}function i(){var e=o.length-1;if(e>=0)return o[e]}var r=!1,o=[];return e.prototype._promiseCreated=function(){},e.prototype._pushContext=function(){},e.prototype._popContext=function(){return null},e._peekContext=e.prototype._peekContext=function(){},t.prototype._pushContext=function(){void 0!==this._trace&&(this._trace._promiseCreated=null,o.push(this._trace))},t.prototype._popContext=function(){if(void 0!==this._trace){var e=o.pop(),t=e._promiseCreated;return e._promiseCreated=null,t}return null},t.CapturedTrace=null,t.create=n,t.deactivateLongStackTraces=function(){},t.activateLongStackTraces=function(){var n=e.prototype._pushContext,o=e.prototype._popContext,s=e._peekContext,a=e.prototype._peekContext,l=e.prototype._promiseCreated;t.deactivateLongStackTraces=function(){e.prototype._pushContext=n,e.prototype._popContext=o,e._peekContext=s,e.prototype._peekContext=a,e.prototype._promiseCreated=l,r=!1},r=!0,e.prototype._pushContext=t.prototype._pushContext,e.prototype._popContext=t.prototype._popContext,e._peekContext=e.prototype._peekContext=i,e.prototype._promiseCreated=function(){var e=this._peekContext();e&&null==e._promiseCreated&&(e._promiseCreated=this)}},t}},{}],9:[function(e,n,exports){"use strict";n.exports=function(n,i){function r(e,t){return{promise:t}}function o(){return!1}function s(e,t,n){var i=this;try{e(t,n,function(e){if("function"!=typeof e)throw new TypeError("onCancel must be a function, got: "+j.toString(e));i._attachCancellationCallback(e)})}catch(e){return e}}function a(e){if(!this._isCancellable())return this;var t=this._onCancel();void 0!==t?j.isArray(t)?t.push(e):this._setOnCancel([t,e]):this._setOnCancel(e)}function l(){return this._onCancelField}function u(e){this._onCancelField=e}function c(){this._cancellationParent=void 0,this._onCancelField=void 0}function h(e,t){if(0!==(1&t)){this._cancellationParent=e;var n=e._branchesRemainingToCancel;void 0===n&&(n=0),e._branchesRemainingToCancel=n+1}0!==(2&t)&&e._isBound()&&this._setBoundTo(e._boundTo)}function d(e,t){0!==(2&t)&&e._isBound()&&this._setBoundTo(e._boundTo)}function f(){var e=this._boundTo;return void 0!==e&&e instanceof n?e.isFulfilled()?e.value():void 0:e}function p(){this._trace=new P(this._peekContext())}function g(e,t){if(z(e)){var n=this._trace;if(void 0!==n&&t&&(n=n._parent),void 0!==n)n.attachExtraTrace(e);else if(!e.__stackCleaned__){var i=A(e);j.notEnumerableProp(e,"stack",i.message+"\n"+i.stack.join("\n")),j.notEnumerableProp(e,"__stackCleaned__",!0)}}}function m(e,t,n,i,r){if(void 0===e&&null!==t&&Q){if(void 0!==r&&r._returnedNonUndefined())return;if(0===(65535&i._bitField))return;n&&(n+=" ");var o="",s="";if(t._trace){for(var a=t._trace.stack.split("\n"),l=x(a),u=l.length-1;u>=0;--u){var c=l[u];if(!U.test(c)){var h=c.match(G);h&&(o="at "+h[1]+":"+h[2]+":"+h[3]+" ");break}}if(l.length>0)for(var d=l[0],u=0;u<a.length;++u)if(a[u]===d){u>0&&(s="\n"+a[u-1]);break}}var f="a promise was created in a "+n+"handler "+o+"but was not returned from it, see http://goo.gl/rRqMUw"+s;i._warn(f,!0,t)}}function v(e,t){var n=e+" is deprecated and will be removed in a future version.";return t&&(n+=" Use "+t+" instead."),y(n)}function y(e,t,i){if(ae.warnings){var r,o=new N(e);if(t)i._attachExtraTrace(o);else if(ae.longStackTraces&&(r=n._peekContext()))r.attachExtraTrace(o);else{var s=A(o);o.stack=s.message+"\n"+s.stack.join("\n")}ne("warning",o)||E(o,"",!0)}}function _(e,t){for(var n=0;n<t.length-1;++n)t[n].push("From previous event:"),t[n]=t[n].join("\n");return n<t.length&&(t[n]=t[n].join("\n")),e+"\n"+t.join("\n")}function b(e){for(var t=0;t<e.length;++t)(0===e[t].length||t+1<e.length&&e[t][0]===e[t+1][0])&&(e.splice(t,1),t--)}function w(e){for(var t=e[0],n=1;n<e.length;++n){for(var i=e[n],r=t.length-1,o=t[r],s=-1,a=i.length-1;a>=0;--a)if(i[a]===o){s=a;break}for(var a=s;a>=0;--a){var l=i[a];if(t[r]!==l)break;t.pop(),r--}t=i}}function x(e){for(var t=[],n=0;n<e.length;++n){var i=e[n],r="    (No stack trace)"===i||W.test(i),o=r&&re(i);r&&!o&&(q&&" "!==i.charAt(0)&&(i="    "+i),t.push(i))}return t}function C(e){for(var t=e.stack.replace(/\s+$/g,"").split("\n"),n=0;n<t.length;++n){var i=t[n];if("    (No stack trace)"===i||W.test(i))break}return n>0&&"SyntaxError"!=e.name&&(t=t.slice(n)),t}function A(e){var t=e.stack,n=e.toString();return t="string"==typeof t&&t.length>0?C(e):["    (No stack trace)"],{message:n,stack:"SyntaxError"==e.name?t:x(t)}}function E(e,t,n){if("undefined"!=typeof console){var i;if(j.isObject(e)){var r=e.stack;i=t+V(r,e)}else i=t+String(e);"function"==typeof O?O(i,n):"function"!=typeof console.log&&"object"!=typeof console.log||console.log(i)}}function S(e,t,n,i){var r=!1;try{"function"==typeof t&&(r=!0,"rejectionHandled"===e?t(i):t(n,i))}catch(e){I.throwLater(e)}"unhandledRejection"===e?ne(e,n,i)||r||E(n,"Unhandled rejection "):ne(e,i)}function F(e){var t;if("function"==typeof e)t="[function "+(e.name||"anonymous")+"]";else{t=e&&"function"==typeof e.toString?e.toString():j.toString(e);var n=/\[object [a-zA-Z0-9$_]+\]/;if(n.test(t))try{var i=JSON.stringify(e);t=i}catch(e){}0===t.length&&(t="(empty array)")}return"(<"+T(t)+">, no stack trace)"}function T(e){var t=41;return e.length<t?e:e.substr(0,t-3)+"..."}function k(){return"function"==typeof se}function D(e){var t=e.match(oe);if(t)return{fileName:t[1],line:parseInt(t[2],10)}}function M(e,t){if(k()){for(var n,i,r=e.stack.split("\n"),o=t.stack.split("\n"),s=-1,a=-1,l=0;l<r.length;++l){var u=D(r[l]);if(u){n=u.fileName,s=u.line;break}}for(var l=0;l<o.length;++l){var u=D(o[l]);if(u){i=u.fileName,a=u.line;break}}s<0||a<0||!n||!i||n!==i||s>=a||(re=function(e){if(H.test(e))return!0;var t=D(e);return!!(t&&t.fileName===n&&s<=t.line&&t.line<=a)})}}function P(e){this._parent=e,this._promisesCreated=0;var t=this._length=1+(void 0===e?0:e._length);se(this,P),t>32&&this.uncycle()}var R,L,O,B=n._getDomain,I=n._async,N=e("./errors").Warning,j=e("./util"),z=j.canAttachTrace,H=/[\\\/]bluebird[\\\/]js[\\\/](release|debug|instrumented)/,U=/\((?:timers\.js):\d+:\d+\)/,G=/[\/<\(](.+?):(\d+):(\d+)\)?\s*$/,W=null,V=null,q=!1,K=!(0==j.env("BLUEBIRD_DEBUG")),Y=!(0==j.env("BLUEBIRD_WARNINGS")||!K&&!j.env("BLUEBIRD_WARNINGS")),X=!(0==j.env("BLUEBIRD_LONG_STACK_TRACES")||!K&&!j.env("BLUEBIRD_LONG_STACK_TRACES")),Q=0!=j.env("BLUEBIRD_W_FORGOTTEN_RETURN")&&(Y||!!j.env("BLUEBIRD_W_FORGOTTEN_RETURN"));n.prototype.suppressUnhandledRejections=function(){var e=this._target();e._bitField=e._bitField&-1048577|524288},n.prototype._ensurePossibleRejectionHandled=function(){0===(524288&this._bitField)&&(this._setRejectionIsUnhandled(),I.invokeLater(this._notifyUnhandledRejection,this,void 0))},n.prototype._notifyUnhandledRejectionIsHandled=function(){S("rejectionHandled",R,void 0,this)},n.prototype._setReturnedNonUndefined=function(){this._bitField=268435456|this._bitField},n.prototype._returnedNonUndefined=function(){return 0!==(268435456&this._bitField)},n.prototype._notifyUnhandledRejection=function(){if(this._isRejectionUnhandled()){var e=this._settledValue();this._setUnhandledRejectionIsNotified(),S("unhandledRejection",L,e,this)}},n.prototype._setUnhandledRejectionIsNotified=function(){this._bitField=262144|this._bitField},n.prototype._unsetUnhandledRejectionIsNotified=function(){this._bitField=this._bitField&-262145},n.prototype._isUnhandledRejectionNotified=function(){return(262144&this._bitField)>0},n.prototype._setRejectionIsUnhandled=function(){this._bitField=1048576|this._bitField},n.prototype._unsetRejectionIsUnhandled=function(){this._bitField=this._bitField&-1048577,this._isUnhandledRejectionNotified()&&(this._unsetUnhandledRejectionIsNotified(),this._notifyUnhandledRejectionIsHandled())},n.prototype._isRejectionUnhandled=function(){return(1048576&this._bitField)>0},n.prototype._warn=function(e,t,n){return y(e,t,n||this)},n.onPossiblyUnhandledRejection=function(e){var t=B();L="function"==typeof e?null===t?e:j.domainBind(t,e):void 0},n.onUnhandledRejectionHandled=function(e){var t=B();R="function"==typeof e?null===t?e:j.domainBind(t,e):void 0};var Z=function(){};n.longStackTraces=function(){if(I.haveItemsQueued()&&!ae.longStackTraces)throw new Error("cannot enable long stack traces after promises have been created\n\n    See http://goo.gl/MqrFmX\n");if(!ae.longStackTraces&&k()){var e=n.prototype._captureStackTrace,t=n.prototype._attachExtraTrace;ae.longStackTraces=!0,Z=function(){if(I.haveItemsQueued()&&!ae.longStackTraces)throw new Error("cannot enable long stack traces after promises have been created\n\n    See http://goo.gl/MqrFmX\n");n.prototype._captureStackTrace=e,n.prototype._attachExtraTrace=t,i.deactivateLongStackTraces(),I.enableTrampoline(),ae.longStackTraces=!1},n.prototype._captureStackTrace=p,n.prototype._attachExtraTrace=g,i.activateLongStackTraces(),I.disableTrampolineIfNecessary()}},n.hasLongStackTraces=function(){return ae.longStackTraces&&k()};var J=function(){try{if("function"==typeof CustomEvent){var e=new CustomEvent("CustomEvent");return j.global.dispatchEvent(e),function(e,t){var n=new CustomEvent(e.toLowerCase(),{detail:t,cancelable:!0});return!j.global.dispatchEvent(n)}}if("function"==typeof Event){var e=new Event("CustomEvent");return j.global.dispatchEvent(e),function(e,t){var n=new Event(e.toLowerCase(),{cancelable:!0});return n.detail=t,!j.global.dispatchEvent(n)}}var e=document.createEvent("CustomEvent");return e.initCustomEvent("testingtheevent",!1,!0,{}),j.global.dispatchEvent(e),function(e,t){var n=document.createEvent("CustomEvent");return n.initCustomEvent(e.toLowerCase(),!1,!0,t),!j.global.dispatchEvent(n)}}catch(e){}return function(){return!1}}(),ee=function(){return j.isNode?function(){return t.emit.apply(t,arguments)}:j.global?function(e){var t="on"+e.toLowerCase(),n=j.global[t];return!!n&&(n.apply(j.global,[].slice.call(arguments,1)),!0)}:function(){return!1}}(),te={promiseCreated:r,promiseFulfilled:r,promiseRejected:r,promiseResolved:r,promiseCancelled:r,promiseChained:function(e,t,n){return{promise:t,child:n}},warning:function(e,t){return{warning:t}},unhandledRejection:function(e,t,n){return{reason:t,promise:n}},rejectionHandled:r},ne=function(e){var t=!1;try{t=ee.apply(null,arguments)}catch(e){I.throwLater(e),t=!0}var n=!1;try{n=J(e,te[e].apply(null,arguments))}catch(e){I.throwLater(e),n=!0}return n||t};n.config=function(e){if(e=Object(e),"longStackTraces"in e&&(e.longStackTraces?n.longStackTraces():!e.longStackTraces&&n.hasLongStackTraces()&&Z()),"warnings"in e){var t=e.warnings;ae.warnings=!!t,Q=ae.warnings,j.isObject(t)&&"wForgottenReturn"in t&&(Q=!!t.wForgottenReturn)}if("cancellation"in e&&e.cancellation&&!ae.cancellation){if(I.haveItemsQueued())throw new Error("cannot enable cancellation after promises are in use");n.prototype._clearCancellationData=c,n.prototype._propagateFrom=h,n.prototype._onCancel=l,n.prototype._setOnCancel=u,n.prototype._attachCancellationCallback=a,n.prototype._execute=s,ie=h,ae.cancellation=!0}return"monitoring"in e&&(e.monitoring&&!ae.monitoring?(ae.monitoring=!0,n.prototype._fireEvent=ne):!e.monitoring&&ae.monitoring&&(ae.monitoring=!1,n.prototype._fireEvent=o)),n},n.prototype._fireEvent=o,n.prototype._execute=function(e,t,n){try{e(t,n)}catch(e){return e}},n.prototype._onCancel=function(){},n.prototype._setOnCancel=function(e){},n.prototype._attachCancellationCallback=function(e){},n.prototype._captureStackTrace=function(){},n.prototype._attachExtraTrace=function(){},n.prototype._clearCancellationData=function(){},n.prototype._propagateFrom=function(e,t){};var ie=d,re=function(){return!1},oe=/[\/<\(]([^:\/]+):(\d+):(?:\d+)\)?\s*$/;j.inherits(P,Error),i.CapturedTrace=P,P.prototype.uncycle=function(){var e=this._length;if(!(e<2)){for(var t=[],n={},i=0,r=this;void 0!==r;++i)t.push(r),r=r._parent;e=this._length=i;for(var i=e-1;i>=0;--i){var o=t[i].stack;void 0===n[o]&&(n[o]=i)}for(var i=0;i<e;++i){var s=t[i].stack,a=n[s];if(void 0!==a&&a!==i){a>0&&(t[a-1]._parent=void 0,t[a-1]._length=1),t[i]._parent=void 0,t[i]._length=1;var l=i>0?t[i-1]:this;a<e-1?(l._parent=t[a+1],l._parent.uncycle(),l._length=l._parent._length+1):(l._parent=void 0,l._length=1);for(var u=l._length+1,c=i-2;c>=0;--c)t[c]._length=u,u++;return}}}},P.prototype.attachExtraTrace=function(e){if(!e.__stackCleaned__){this.uncycle();for(var t=A(e),n=t.message,i=[t.stack],r=this;void 0!==r;)i.push(x(r.stack.split("\n"))),r=r._parent;w(i),b(i),j.notEnumerableProp(e,"stack",_(n,i)),j.notEnumerableProp(e,"__stackCleaned__",!0)}};var se=function(){var e=/^\s*at\s*/,t=function(e,t){return"string"==typeof e?e:void 0!==t.name&&void 0!==t.message?t.toString():F(t)};if("number"==typeof Error.stackTraceLimit&&"function"==typeof Error.captureStackTrace){Error.stackTraceLimit+=6,W=e,V=t;var n=Error.captureStackTrace;return re=function(e){return H.test(e)},function(e,t){Error.stackTraceLimit+=6,n(e,t),Error.stackTraceLimit-=6}}var i=new Error;if("string"==typeof i.stack&&i.stack.split("\n")[0].indexOf("stackDetection@")>=0)return W=/@/,V=t,q=!0,function(e){e.stack=(new Error).stack};var r;try{throw new Error}catch(e){r="stack"in e}return"stack"in i||!r||"number"!=typeof Error.stackTraceLimit?(V=function(e,t){return"string"==typeof e?e:"object"!=typeof t&&"function"!=typeof t||void 0===t.name||void 0===t.message?F(t):t.toString()},null):(W=e,V=t,function(e){Error.stackTraceLimit+=6;try{throw new Error}catch(t){e.stack=t.stack}Error.stackTraceLimit-=6})}([]);"undefined"!=typeof console&&"undefined"!=typeof console.warn&&(O=function(e){console.warn(e)},j.isNode&&t.stderr.isTTY?O=function(e,t){var n=t?"[33m":"[31m";console.warn(n+e+"[0m\n")}:j.isNode||"string"!=typeof(new Error).stack||(O=function(e,t){console.warn("%c"+e,t?"color: darkorange":"color: red")}));var ae={warnings:Y,longStackTraces:!1,cancellation:!1,monitoring:!1};return X&&n.longStackTraces(),{longStackTraces:function(){return ae.longStackTraces},warnings:function(){return ae.warnings},cancellation:function(){return ae.cancellation},monitoring:function(){return ae.monitoring},propagateFromFunction:function(){return ie},boundValueFunction:function(){return f},checkForgottenReturns:m,setBounds:M,warn:y,deprecated:v,CapturedTrace:P,fireDomEvent:J,fireGlobalEvent:ee}}},{"./errors":12,"./util":36}],10:[function(e,t,exports){"use strict";t.exports=function(e){function t(){return this.value}function n(){throw this.reason}e.prototype.return=e.prototype.thenReturn=function(n){return n instanceof e&&n.suppressUnhandledRejections(),this._then(t,void 0,void 0,{value:n},void 0)},e.prototype.throw=e.prototype.thenThrow=function(e){return this._then(n,void 0,void 0,{reason:e},void 0)},e.prototype.catchThrow=function(e){if(arguments.length<=1)return this._then(void 0,n,void 0,{reason:e},void 0);var t=arguments[1],i=function(){throw t};return this.caught(e,i)},e.prototype.catchReturn=function(n){if(arguments.length<=1)return n instanceof e&&n.suppressUnhandledRejections(),this._then(void 0,t,void 0,{value:n},void 0);var i=arguments[1];i instanceof e&&i.suppressUnhandledRejections();var r=function(){return i};return this.caught(n,r)}}},{}],11:[function(e,t,exports){"use strict";t.exports=function(e,t){function n(){return o(this)}function i(e,n){return r(e,n,t,t)}var r=e.reduce,o=e.all;e.prototype.each=function(e){return r(this,e,t,0)._then(n,void 0,void 0,this,void 0)},e.prototype.mapSeries=function(e){return r(this,e,t,t)},e.each=function(e,i){return r(e,i,t,0)._then(n,void 0,void 0,e,void 0)},e.mapSeries=i}},{}],12:[function(e,t,exports){"use strict";function n(e,t){function n(i){return this instanceof n?(c(this,"message","string"==typeof i?i:t),c(this,"name",e),void(Error.captureStackTrace?Error.captureStackTrace(this,this.constructor):Error.call(this))):new n(i)}return u(n,Error),n}function i(e){return this instanceof i?(c(this,"name","OperationalError"),c(this,"message",e),this.cause=e,this.isOperational=!0,void(e instanceof Error?(c(this,"message",e.message),c(this,"stack",e.stack)):Error.captureStackTrace&&Error.captureStackTrace(this,this.constructor))):new i(e)}var r,o,s=e("./es5"),a=s.freeze,l=e("./util"),u=l.inherits,c=l.notEnumerableProp,h=n("Warning","warning"),d=n("CancellationError","cancellation error"),f=n("TimeoutError","timeout error"),p=n("AggregateError","aggregate error");try{r=TypeError,o=RangeError}catch(e){r=n("TypeError","type error"),o=n("RangeError","range error")}for(var g="join pop push shift unshift slice filter forEach some every map indexOf lastIndexOf reduce reduceRight sort reverse".split(" "),m=0;m<g.length;++m)"function"==typeof Array.prototype[g[m]]&&(p.prototype[g[m]]=Array.prototype[g[m]]);s.defineProperty(p.prototype,"length",{value:0,configurable:!1,writable:!0,enumerable:!0}),p.prototype.isOperational=!0;var v=0;p.prototype.toString=function(){var e=Array(4*v+1).join(" "),t="\n"+e+"AggregateError of:\n";v++,e=Array(4*v+1).join(" ");for(var n=0;n<this.length;++n){for(var i=this[n]===this?"[Circular AggregateError]":this[n]+"",r=i.split("\n"),o=0;o<r.length;++o)r[o]=e+r[o];i=r.join("\n"),t+=i+"\n"}return v--,t},u(i,Error);var y=Error.__BluebirdErrorTypes__;y||(y=a({CancellationError:d,TimeoutError:f,OperationalError:i,RejectionError:i,AggregateError:p}),s.defineProperty(Error,"__BluebirdErrorTypes__",{value:y,writable:!1,enumerable:!1,configurable:!1})),t.exports={Error:Error,TypeError:r,RangeError:o,CancellationError:y.CancellationError,OperationalError:y.OperationalError,TimeoutError:y.TimeoutError,AggregateError:y.AggregateError,Warning:h}},{"./es5":13,"./util":36}],13:[function(e,t,exports){var n=function(){"use strict";return void 0===this}();if(n)t.exports={freeze:Object.freeze,defineProperty:Object.defineProperty,getDescriptor:Object.getOwnPropertyDescriptor,keys:Object.keys,names:Object.getOwnPropertyNames,getPrototypeOf:Object.getPrototypeOf,isArray:Array.isArray,isES5:n,propertyIsWritable:function(e,t){var n=Object.getOwnPropertyDescriptor(e,t);return!(n&&!n.writable&&!n.set)}};else{var i={}.hasOwnProperty,r={}.toString,o={}.constructor.prototype,s=function(e){var t=[];for(var n in e)i.call(e,n)&&t.push(n);return t},a=function(e,t){return{value:e[t]}},l=function(e,t,n){return e[t]=n.value,e},u=function(e){return e},c=function(e){try{return Object(e).constructor.prototype}catch(e){return o}},h=function(e){try{return"[object Array]"===r.call(e)}catch(e){return!1}};t.exports={isArray:h,keys:s,names:s,defineProperty:l,getDescriptor:a,freeze:u,getPrototypeOf:c,isES5:n,propertyIsWritable:function(){return!0}}}},{}],14:[function(e,t,exports){"use strict";t.exports=function(e,t){var n=e.map;e.prototype.filter=function(e,i){return n(this,e,i,t)},e.filter=function(e,i,r){return n(e,i,r,t)}}},{}],15:[function(e,t,exports){"use strict";t.exports=function(t,n){function i(e,t,n){this.promise=e,this.type=t,this.handler=n,this.called=!1,this.cancelPromise=null}function r(e){this.finallyHandler=e}function o(e,t){return null!=e.cancelPromise&&(arguments.length>1?e.cancelPromise._reject(t):e.cancelPromise._cancel(),e.cancelPromise=null,!0)}function s(){return l.call(this,this.promise._target()._settledValue())}function a(e){if(!o(this,e))return h.e=e,h}function l(e){var i=this.promise,l=this.handler;if(!this.called){this.called=!0;var u=this.isFinallyHandler()?l.call(i._boundValue()):l.call(i._boundValue(),e);if(void 0!==u){i._setReturnedNonUndefined();var d=n(u,i);if(d instanceof t){if(null!=this.cancelPromise){if(d._isCancelled()){var f=new c("late cancellation observer");return i._attachExtraTrace(f),h.e=f,h}d.isPending()&&d._attachCancellationCallback(new r(this))}return d._then(s,a,void 0,this,void 0)}}}return i.isRejected()?(o(this),h.e=e,h):(o(this),e)}var u=e("./util"),c=t.CancellationError,h=u.errorObj;return i.prototype.isFinallyHandler=function(){return 0===this.type},r.prototype._resultCancelled=function(){o(this.finallyHandler)},t.prototype._passThrough=function(e,t,n,r){return"function"!=typeof e?this.then():this._then(n,r,void 0,new i(this,t,e),void 0)},t.prototype.lastly=t.prototype.finally=function(e){return this._passThrough(e,0,l,l)},t.prototype.tap=function(e){return this._passThrough(e,1,l)},i}},{"./util":36}],16:[function(e,t,exports){"use strict";t.exports=function(t,n,i,r,o,s){function a(e,n,i){for(var o=0;o<n.length;++o){i._pushContext();var s=f(n[o])(e);if(i._popContext(),s===d){i._pushContext();var a=t.reject(d.e);return i._popContext(),a}var l=r(s,i);if(l instanceof t)return l}return null}function l(e,n,r,o){if(s.cancellation()){var a=new t(i),l=this._finallyPromise=new t(i);this._promise=a.lastly(function(){return l}),a._captureStackTrace(),a._setOnCancel(this)}else{var u=this._promise=new t(i);u._captureStackTrace()}this._stack=o,this._generatorFunction=e,this._receiver=n,this._generator=void 0,this._yieldHandlers="function"==typeof r?[r].concat(p):p,this._yieldedPromise=null,this._cancellationPhase=!1}var u=e("./errors"),c=u.TypeError,h=e("./util"),d=h.errorObj,f=h.tryCatch,p=[];h.inherits(l,o),l.prototype._isResolved=function(){return null===this._promise},l.prototype._cleanup=function(){this._promise=this._generator=null,s.cancellation()&&null!==this._finallyPromise&&(this._finallyPromise._fulfill(),this._finallyPromise=null)},l.prototype._promiseCancelled=function(){if(!this._isResolved()){var e,n="undefined"!=typeof this._generator.return;if(n)this._promise._pushContext(),e=f(this._generator.return).call(this._generator,void 0),this._promise._popContext();else{var i=new t.CancellationError("generator .return() sentinel");t.coroutine.returnSentinel=i,this._promise._attachExtraTrace(i),this._promise._pushContext(),e=f(this._generator.throw).call(this._generator,i),this._promise._popContext()}this._cancellationPhase=!0,this._yieldedPromise=null,this._continue(e)}},l.prototype._promiseFulfilled=function(e){this._yieldedPromise=null,this._promise._pushContext();var t=f(this._generator.next).call(this._generator,e);this._promise._popContext(),this._continue(t)},l.prototype._promiseRejected=function(e){this._yieldedPromise=null,this._promise._attachExtraTrace(e),this._promise._pushContext();var t=f(this._generator.throw).call(this._generator,e);this._promise._popContext(),this._continue(t)},l.prototype._resultCancelled=function(){if(this._yieldedPromise instanceof t){var e=this._yieldedPromise;this._yieldedPromise=null,e.cancel()}},l.prototype.promise=function(){return this._promise},l.prototype._run=function(){this._generator=this._generatorFunction.call(this._receiver),this._receiver=this._generatorFunction=void 0,this._promiseFulfilled(void 0)},l.prototype._continue=function(e){var n=this._promise;if(e===d)return this._cleanup(),this._cancellationPhase?n.cancel():n._rejectCallback(e.e,!1);var i=e.value;if(e.done===!0)return this._cleanup(),this._cancellationPhase?n.cancel():n._resolveCallback(i);var o=r(i,this._promise);if(!(o instanceof t)&&(o=a(o,this._yieldHandlers,this._promise),null===o))return void this._promiseRejected(new c("A value %s was yielded that could not be treated as a promise\n\n    See http://goo.gl/MqrFmX\n\n".replace("%s",i)+"From coroutine:\n"+this._stack.split("\n").slice(1,-7).join("\n")));o=o._target();var s=o._bitField;0===(50397184&s)?(this._yieldedPromise=o,o._proxy(this,null)):0!==(33554432&s)?t._async.invoke(this._promiseFulfilled,this,o._value()):0!==(16777216&s)?t._async.invoke(this._promiseRejected,this,o._reason()):this._promiseCancelled()},t.coroutine=function(e,t){if("function"!=typeof e)throw new c("generatorFunction must be a function\n\n    See http://goo.gl/MqrFmX\n");var n=Object(t).yieldHandler,i=l,r=(new Error).stack;return function(){var t=e.apply(this,arguments),o=new i(void 0,void 0,n,r),s=o.promise();return o._generator=t,o._promiseFulfilled(void 0),s}},t.coroutine.addYieldHandler=function(e){if("function"!=typeof e)throw new c("expecting a function but got "+h.classString(e));p.push(e)},t.spawn=function(e){if(s.deprecated("Promise.spawn()","Promise.coroutine()"),"function"!=typeof e)return n("generatorFunction must be a function\n\n    See http://goo.gl/MqrFmX\n");"_

I have deleted all pipelines that reference the TIP function (but not the rules themselves, as ideally I'd like to keep them).  I can delete them if required if their mere presence in the config is causing the issue, but will have to take copies etc as there is no ability to disable (feature request!).

Rgds

**Comment by edmundoa** [comment]
Thank you for the information! I don't think it's necessary to delete the rules, but I'm still unsure what is wrong. Do you see the reload in all pages?

Would you also be so kind as to share with us the plugin versions you are using? You can find them at the start of the server log or in your "System -> Nodes -> <Node>" page, in the "installed plugins" section.

**Comment by urban-moniker** [comment]
Hi,

Plugin info at bottom.  For your other questions (and a bit of testing).

We get the reload on every page as far as I can tell (on each "tab" and subtabs under System etc):-

- Reload period is a constant 20 second period.
- If I browse to a new page within this 20 second window the new page reloads on the 'original' mark i.e. the 20 second timer does not 'restart' so if I change pages after 10 seconds the new page reloads after 10 seconds etc.

-----
Aggregates	0.0.12	Christiaan van Tienhoven	Graylog Aggregates plugin  Website
Anonymous Usage Statistics	2.2.0-beta.4	Graylog, Inc.	A plugin for collecting anonymous usages statistics about Graylog nodes and clusters.  Website
CEF Input	1.0.0	Lennart Koopmann <lennart@graylog.com>	Input plugin to receive CEF (Common Event Format) messages.  Website
Collector	2.2.0-beta.4	Graylog, Inc.	Collectors plugin  Website
Elastic Beats Input	2.2.0-beta.4	Graylog, Inc.	Input plugin for Elastic Beats (Beats/Lumberjack protocol).  Website
Enterprise Integration Plugin	2.2.0-beta.4	Graylog, Inc	Provides basic integration with Graylog Enterprise  Website
ExeCommandAlarmCallBack	1.0.0	ahmad.niksefat@gmail.com	A graylog2 alarm callback for executing commands on server.  Website
MapWidgetPlugin	2.2.0-beta.4	Graylog, Inc.	Map widget for Graylog  Website
Pipeline Processor Plugin	2.2.0-beta.4	Graylog, Inc	Pluggable pipeline processing framework  Website
SnmpPlugin	0.3.0	Graylog, Inc.	SNMP plugins  Website
SyslogOutput	1.0.0	Wizecore. Based on work by Intelie.	Enables sending messages to syslog.  Website

Hope this helps

**Comment by edmundoa** [comment]
I would try moving out all plugins that are not part of the release, just to be sure they are not the source of the issue. From the list you posted, I would start moving out: Aggregates, CEF Input, ExeCommandAlarmCallBack, SnmpPlugin, and SyslogOutput. If after removing them you don't see the issue any more, there's a good chance one of them is responsible for the reloads. In that case please add them back one by one until you find the culprit.

Additionally, looking back to the last error dump you kindly shared with us, all errors I can see come from one of the libraries we use. Could you please tell us which browser you use to try to reproduce the issue?

Thank you.

**Comment by urban-moniker** [comment]
Will do - all errors were reproduced in Firefox (50.1.0)

**Comment by urban-moniker** [comment]
Hi - I've removed all but those with a version of "2.2.0-beta.4" as suggested and no joy on that.

However, as your last response implied I think, when using IE rather than FF the issue does not appear, so it looks to be FF related.  I'll try re-adding the plugins to see if any create issues in IE as well.

Rgds

**Comment by edmundoa** [comment]
Odd, lately I have been testing the new release with Firefox and didn't see this issue. Maybe there's something "funny" in your browser cache. I would try that after re-adding all plugins and see if it helps.

**Comment by edmundoa** [comment]
Hi @urban-moniker,

Could you please take a look and tell us if the issue you described here is still present in 2.2.0-beta.6?

Thank you!

**Comment by urban-moniker** [comment]
Hi - this looks better - working in FF now.

I did have some issues with IE as well with this version, until I cleared the cache.  Looks like it may be to do with some elements being cached in browers across version upgrades etc (though not my area of expertise).

Either way, on Beta 6 I have it working on both IE and FF.

Now to start working thorugh how best to use the new multiple index\pipeline processing functions (very cool btw!).

**Comment by jalogisch** [comment]
as this looks like a fixed issue this will be closed.
