### ISSUE TITLE
Edit Extractor Page Load Is Slow

### ISSUE THREAD

**Issue by sre-jon** [Graylog2/graylog2-server#3513]
## Expected Behavior

When editing an extractor, the page load should be a couple seconds or less.

## Current Behavior

When editing an extractor, the page load can take over a minute. It appears to be waiting for this page load:
```
Request Headers
Provisional headers are shown
Accept:application/json
Authorization:Basic Njc4NTI0MzYtZmJjYi00NmM5LTlhMmItNGEyZjkyYTZiOWE0OnNlc3Npb24=
Content-Type:application/json
Origin:http://graylog.apixio.com
Referer:http://graylog.apixio.com/system/inputs/56553dd3-e7cd-4d9e-8d36-ed19aca72a12/5769bf8bdd0bf12a681337b2/extractors/8ad2f3e0-f2fc-11e6-96fc-02925234216b/edit
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
X-Requested-With:XMLHttpRequest
Query String Parameters
view source
view URL encoded
query:gl2_source_input:5769bf8bdd0bf12a681337b2 OR gl2_source_radio_input:5769bf8bdd0bf12a681337b2
limit:1
```

## Possible Solution

When running the query from the slow request manually it completes fast. I am guessing there is no time limit used when executing the query during the extractor edit page load so it takes forever when you have a ton of indices.

## Steps to Reproduce (for bugs)

1. Have an environment with 800 indices of ~1 gb each.
2. Go to Input >> Extractors
3. Click edit for an extractor.

## Context

It is slightly annoying, but not the end of the world. I just figured I'd create an issue for it since I was already creating an issue for something else.

## Your Environment

Graylog Version: 2.1.3
Elasticsearch Version: 2.3.3-1
MongoDB Version:3.2.7-1.el7
Operating System: CentOS Linux release 7.2.1511 (Core)
Browser version: chrome 52.0.2743.116 (64-bit) on mac osx

800 indices of ~1gb each

**Comment by jalogisch** [comment]
@sre-jon please update to the latest 2.2 release.

This issue is fixed: https://github.com/Graylog2/graylog2-server/pull/3367

**Comment by sre-jon** [comment]
Thank you.

**Comment by clausa** [comment]
Hi,

Hmm, I'm on Graylog 2.2.3+7adc95 and still having this issue. 

/api/search/universal/relative?query=gl2_source_input%3A573b946de4b09bcceb0d5c8d%20OR%20gl2_source_radio_input%3A573b946de4b09bcceb0d5c8d&limit=1 ends with a "504 gateway timeout" after 1 minute and then things just hangs.

**Comment by joschi** [comment]
@clausa Make sure that your Elasticsearch cluster is able to respond within the configured Elasticsearch request timeout (https://github.com/Graylog2/graylog2-server/blob/2.2.3/misc/graylog.conf#L323-L326).
