### ISSUE TITLE
File path with spaces not escaped properly in Show surrounding messages

### ISSUE THREAD

**Issue by epanoff** [Graylog2/graylog2-server#6999]
File path with spaces not escaped properly in "Show surrounding messages"

## Expected Behavior
Messages are shown while having a properly escaped path separator in file field filter condition

## Current Behavior
No search result due to incorrect filter condition

## Possible Solution
Escape spaces.

## Steps to Reproduce (for bugs)
Select a message in the log with space in path.
Show surrounding messages

![image-2019-12-16-13-03-36-187](https://user-images.githubusercontent.com/10167961/70906651-ef56c800-2017-11ea-8d71-e82510126938.png)
![image-2019-12-16-13-04-51-309](https://user-images.githubusercontent.com/10167961/70906656-f1b92200-2017-11ea-8613-3038a9f82351.png)

## Your Environment

* Graylog Version: 2.5.0-3
* Elasticsearch Version: 6.7.0-1
* MongoDB Version: 3.6.11-1
* Operating System: CentOS Linux release 7.6.1810
* Browser version: Google Chrome 79.0.3945.79

**Comment by jalogisch** [comment]
dear @epanoff 

please update to a later release - this issue is already fixed.

**Comment by epanoff** [comment]
Hello, @jalogisch  
I have updated to Graylog 3.1.4.  And the issue is not fixed. 

![Снимок экрана 2020-02-12 в 13 37 59](https://user-images.githubusercontent.com/10167961/74327670-a31ccf80-4d9d-11ea-92a0-3fa57b5148f6.jpg)
