### ISSUE TITLE
Dashboards page will not load after upgrade to 3.2

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog2-server#7287]
After upgrading from 3.1.3 to 3.2, the Dashboards page loads with errors. The following error is logged. There were 5 dashboards installed from the following content pack. The dashboards were working successfully before the upgrade.

This was tested with a production build. My Enterprise license is expired. Not sure if that impacts this at all.

<details>
 <summary>Exception</summary>
2020-01-24 22:05:31,108 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:67) ~[graylog.jar:?]
	at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:49) ~[graylog.jar:?]
	at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:29) ~[graylog.jar:?]
	at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52) ~[graylog.jar:?]
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41) ~[graylog.jar:?]
	at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101) ~[graylog.jar:?]
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41) ~[graylog.jar:?]
	at com.mongodb.connection.ReplyMessage.<init>(ReplyMessage.java:51) ~[graylog.jar:?]
	at com.mongodb.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:301) ~[graylog.jar:?]
	at com.mongodb.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255) ~[graylog.jar:?]
	at com.mongodb.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:98) ~[graylog.jar:?]
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:441) ~[graylog.jar:?]
	at com.mongodb.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:80) ~[graylog.jar:?]
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:189) ~[graylog.jar:?]
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:264) ~[graylog.jar:?]
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:126) ~[graylog.jar:?]
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:118) ~[graylog.jar:?]
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:226) ~[graylog.jar:?]
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:217) ~[graylog.jar:?]
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:120) ~[graylog.jar:?]
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:717) ~[graylog.jar:?]
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:711) ~[graylog.jar:?]
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:471) ~[graylog.jar:?]
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:415) ~[graylog.jar:?]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:711) ~[graylog.jar:?]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:83) ~[graylog.jar:?]
	at com.mongodb.Mongo$3.execute(Mongo.java:826) ~[graylog.jar:?]
	at com.mongodb.Mongo$3.execute(Mongo.java:813) ~[graylog.jar:?]
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:877) ~[graylog.jar:?]
	at com.mongodb.DBCursor.hasNext(DBCursor.java:144) ~[graylog.jar:?]
	at org.mongojack.DBCursor.hasNext(DBCursor.java:330) ~[graylog.jar:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:115) ~[?:1.8.0_201]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_201]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_201]
	at java.util.stream.LongPipeline.reduce(LongPipeline.java:438) ~[?:1.8.0_201]
	at java.util.stream.LongPipeline.sum(LongPipeline.java:396) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526) ~[?:1.8.0_201]
	at org.graylog2.database.PaginatedDbService.findPaginatedWithQueryFilterAndSort(PaginatedDbService.java:158) ~[graylog.jar:?]
	at org.graylog.plugins.views.search.views.ViewService.searchPaginated(ViewService.java:64) ~[graylog.jar:?]
	at org.graylog.plugins.views.search.views.ViewService.searchPaginatedByType(ViewService.java:86) ~[graylog.jar:?]
	at org.graylog.plugins.views.search.rest.DashboardsResource.views(DashboardsResource.java:88) ~[graylog.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "dashboard_state" (class org.graylog.plugins.views.search.views.$AutoValue_ViewDTO$Builder), not marked as ignorable (11 known properties: "state", "search_id", "properties", "summary", "title", "_id", "description", "requires", "owner", "created_at", "type"])
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@18f40060; pos: 1310] (through reference chain: org.graylog.plugins.views.search.views.$AutoValue_ViewDTO$Builder["dashboard_state"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:274) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:193) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3985) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2343) ~[graylog.jar:?]
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:80) ~[graylog.jar:?]
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:64) ~[graylog.jar:?]
	... 75 more
</details>

<details>
<summary>Server log output from first startup after upgrade</summary>
2020-01-24 22:03:43,052 INFO : org.graylog2.bootstrap.ServerBootstrap - Graylog server 3.2.0-beta.4-SNAPSHOT+cb33786 starting up
2020-01-24 22:03:43,053 INFO : org.graylog2.bootstrap.ServerBootstrap - JRE: Oracle Corporation 1.8.0_201 on Linux 4.14.106-97.85.amzn2.x86_64
2020-01-24 22:03:43,053 INFO : org.graylog2.bootstrap.ServerBootstrap - Deployment: unknown
2020-01-24 22:03:43,053 INFO : org.graylog2.bootstrap.ServerBootstrap - OS: Amazon Linux 2 (amzn)
2020-01-24 22:03:43,053 INFO : org.graylog2.bootstrap.ServerBootstrap - Arch: amd64
2020-01-24 22:03:43,084 INFO : org.graylog2.shared.initializers.PeriodicalsService - Starting 35 periodicals ...
2020-01-24 22:03:43,084 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ThroughputCalculator] periodical in [0s], polling every [1s].
2020-01-24 22:03:43,093 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.pipelineprocessor.periodical.LegacyDefaultStreamMigration] periodical, running forever.
2020-01-24 22:03:43,094 INFO : org.graylog2.shared.initializers.PeriodicalsService - Not starting [org.graylog2.periodical.AlertScannerThread] periodical. Not configured to run on this node.
2020-01-24 22:03:43,095 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] periodical in [0s], polling every [1s].
2020-01-24 22:03:43,095 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ClusterHealthCheckThread] periodical in [120s], polling every [20s].
2020-01-24 22:03:43,096 INFO : org.graylog2.shared.initializers.PeriodicalsService - Not starting [org.graylog2.periodical.ContentPackLoaderPeriodical] periodical. Not configured to run on this node.
2020-01-24 22:03:43,096 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.GarbageCollectionWarningThread] periodical, running forever.
2020-01-24 22:03:43,096 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexerClusterCheckerThread] periodical in [0s], polling every [30s].
2020-01-24 22:03:43,097 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexRetentionThread] periodical in [0s], polling every [300s].
2020-01-24 22:03:43,097 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexRotationThread] periodical in [0s], polling every [10s].
2020-01-24 22:03:43,097 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.NodePingThread] periodical in [0s], polling every [1s].
2020-01-24 22:03:43,098 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.VersionCheckThread] periodical in [300s], polling every [1800s].
2020-01-24 22:03:43,099 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ThrottleStateUpdaterThread] periodical in [1s], polling every [1s].
2020-01-24 22:03:43,099 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.events.ClusterEventPeriodical] periodical in [0s], polling every [1s].
2020-01-24 22:03:43,100 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.events.ClusterEventCleanupPeriodical] periodical in [0s], polling every [86400s].
2020-01-24 22:03:43,100 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ClusterIdGeneratorPeriodical] periodical, running forever.
2020-01-24 22:03:43,101 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexRangesMigrationPeriodical] periodical, running forever.
2020-01-24 22:03:43,102 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexRangesCleanupPeriodical] periodical in [15s], polling every [3600s].
2020-01-24 22:03:43,122 INFO : org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:5}] to localhost:27017
2020-01-24 22:03:43,131 INFO : org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:6}] to localhost:27017
2020-01-24 22:03:43,138 INFO : org.graylog2.shared.initializers.PeriodicalsService - Not starting [org.graylog2.periodical.UserPermissionMigrationPeriodical] periodical. Not configured to run on this node.
2020-01-24 22:03:43,138 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ConfigurationManagementPeriodical] periodical, running forever.
2020-01-24 22:03:43,140 INFO : org.mongodb.driver.connection - Opened connection [connectionId{localValue:7, serverValue:7}] to localhost:27017
2020-01-24 22:03:43,140 INFO : org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:4}] to localhost:27017
2020-01-24 22:03:43,141 INFO : org.mongodb.driver.connection - Opened connection [connectionId{localValue:8, serverValue:8}] to localhost:27017
2020-01-24 22:03:43,152 INFO : org.graylog.plugins.pipelineprocessor.periodical.LegacyDefaultStreamMigration - Legacy default stream has no connections, no migration needed.
2020-01-24 22:03:43,160 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.LdapGroupMappingMigration] periodical, running forever.
2020-01-24 22:03:43,161 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexFailuresPeriodical] periodical, running forever.
2020-01-24 22:03:43,161 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.TrafficCounterCalculator] periodical in [0s], polling every [1s].
2020-01-24 22:03:43,165 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical] periodical in [0s], polling every [3600s].
2020-01-24 22:03:43,166 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.scheduler.periodicals.ScheduleTriggerCleanUp] periodical in [120s], polling every [86400s].
2020-01-24 22:03:43,166 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.sidecar.periodical.PurgeExpiredSidecarsThread] periodical in [0s], polling every [600s].
2020-01-24 22:03:43,166 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.sidecar.periodical.PurgeExpiredConfigurationUploads] periodical in [0s], polling every [600s].
2020-01-24 22:03:43,182 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.views.search.db.SearchesCleanUpJob] periodical in [3600s], polling every [28800s].
2020-01-24 22:03:43,191 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.events.periodicals.EventNotificationStatusCleanUp] periodical in [120s], polling every [86400s].
2020-01-24 22:03:43,196 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.collector.periodical.PurgeExpiredCollectorsThread] periodical in [0s], polling every [3600s].
2020-01-24 22:03:43,205 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.license.LicenseManagerPeriodical] periodical in [0s], polling every [300s].
2020-01-24 22:03:43,221 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.license.LicenseReportPeriodical] periodical in [300s], polling every [3600s].
2020-01-24 22:03:43,224 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.auditlog.mongodb.MongoAuditLogPeriodical] periodical in [0s], polling every [3600s].
2020-01-24 22:03:43,225 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.report.scheduler.ReportPeriodical] periodical in [120s], polling every [60s].
2020-01-24 22:03:43,226 ERROR: org.graylog.plugins.auditlog.mongodb.MongoAuditLogPeriodical - Not running cleanup for auditlog entries in MongoDB because there is no valid license.
2020-01-24 22:03:43,226 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.report.service.ChromeDriverCleanupPeriodical] periodical in [60s], polling every [180s].
2020-01-24 22:03:43,270 INFO : org.graylog2.lookup.LookupTableService - Data Adapter cloudflare-geo-lookup-table/5e0dd83795125a1023c2db57 [@1f64d005] STARTING
2020-01-24 22:03:43,272 INFO : org.graylog2.lookup.LookupTableService - Data Adapter cloudflare-threat-lookup-adaptor/5e0dd83795125a1023c2db37 [@7c8be05c] STARTING
2020-01-24 22:03:43,304 INFO : org.graylog2.lookup.LookupTableService - Data Adapter cloudflare-threat-lookup-adaptor/5e0dd83795125a1023c2db37 [@7c8be05c] RUNNING
2020-01-24 22:03:43,304 INFO : org.graylog2.lookup.LookupDataAdapterRefreshService - Adding job for <cloudflare-threat-lookup-adaptor/5e0dd83795125a1023c2db37/@7c8be05c> [interval=60000ms]
2020-01-24 22:03:43,326 INFO : org.graylog2.lookup.LookupTableService - Data Adapter cloudflare-geo-lookup-table/5e0dd83795125a1023c2db57 [@1f64d005] RUNNING
2020-01-24 22:03:43,327 INFO : org.graylog2.lookup.LookupDataAdapterRefreshService - Adding job for <cloudflare-geo-lookup-table/5e0dd83795125a1023c2db57/@1f64d005> [interval=60000ms]
2020-01-24 22:03:43,536 INFO : org.graylog2.lookup.LookupTableService - Cache geo-cache/5e0dd83795125a1023c2db35 [@101508f6] STARTING
2020-01-24 22:03:43,551 INFO : org.graylog2.lookup.LookupTableService - Cache no-cache/5e0dd83795125a1023c2db5f [@1a2e35f] STARTING
2020-01-24 22:03:43,552 INFO : org.graylog2.lookup.LookupTableService - Cache no-cache/5e0dd83795125a1023c2db5f [@1a2e35f] RUNNING
2020-01-24 22:03:43,552 INFO : org.graylog2.lookup.LookupTableService - Cache geo-cache/5e0dd83795125a1023c2db35 [@101508f6] RUNNING
2020-01-24 22:03:43,560 INFO : org.graylog2.lookup.LookupTableService - Starting lookup table cloudflare-geo-lookup-table/5e0dd83795125a1023c2db5b [@592a9c6f] using cache geo-cache/5e0dd83795125a1023c2db35 [@101508f6], data adapter cloudflare-geo-lookup-table/5e0dd83795125a1023c2db57 [@1f64d005]
2020-01-24 22:03:43,561 INFO : org.graylog2.lookup.LookupTableService - Starting lookup table cloudflare-threat-lookup-table/5e0dd83795125a1023c2db61 [@3a534136] using cache no-cache/5e0dd83795125a1023c2db5f [@1a2e35f], data adapter cloudflare-threat-lookup-adaptor/5e0dd83795125a1023c2db37 [@7c8be05c]
2020-01-24 22:03:44,288 ERROR: org.graylog2.migrations.MigrationHelpers - Invalid user 'graylog-report', fixing it.
2020-01-24 22:03:44,293 INFO : org.graylog2.migrations.MigrationHelpers - graylog-report user is missing or invalid, re-adding it as a built-in user.
2020-01-24 22:03:44,517 INFO : org.graylog2.shared.initializers.JerseyService - Enabling CORS for HTTP endpoint
2020-01-24 22:04:10,468 INFO : org.glassfish.grizzly.http.server.NetworkListener - Started listener bound to [10.0.0.67:8080]
2020-01-24 22:04:10,470 INFO : org.glassfish.grizzly.http.server.HttpServer - [HttpServer] Started.
2020-01-24 22:04:10,470 INFO : org.graylog2.shared.initializers.JerseyService - Started REST API at <10.0.0.67:8080>
2020-01-24 22:04:10,471 INFO : org.graylog2.shared.initializers.ServiceManagerListener - Services are healthy
2020-01-24 22:04:10,472 INFO : org.graylog2.bootstrap.ServerBootstrap - Services started, startup times in ms: {OutputSetupService [RUNNING]=25, BufferSynchronizerService [RUNNING]=25, GracefulShutdownService [RUNNING]=26, KafkaJournal [RUNNING]=49, ConfigurationEtagService [RUNNING]=89, JobSchedulerService [RUNNING]=124, JournalReader [RUNNING]=125, UrlWhitelistService [RUNNING]=129, InputSetupService [RUNNING]=132, EtagService [RUNNING]=157, PeriodicalsService [RUNNING]=185, StreamCacheService [RUNNING]=190, MongoDBProcessingStatusRecorderService [RUNNING]=191, LookupTableService [RUNNING]=479, JerseyService [RUNNING]=27390}
2020-01-24 22:04:10,473 INFO : org.graylog2.shared.initializers.InputSetupService - Triggering launching persisted inputs, node transitioned from Uninitialized [LB:DEAD] to Running [LB:ALIVE]
2020-01-24 22:04:10,480 INFO : org.graylog2.bootstrap.ServerBootstrap - Graylog server up and running.
2020-01-24 22:04:10,480 ERROR: org.graylog.plugins.auditlog.AuditLogger - Unable to write audit log entry because there is no valid license.
2020-01-24 22:04:10,537 INFO : org.graylog2.inputs.InputStateListener - Input [GELF TCP/5e0dd83795125a1023c2db74] is now STARTING
2020-01-24 22:04:10,538 INFO : org.graylog2.inputs.InputStateListener - Input [Raw/Plaintext UDP/5e2b610095125a0f07a78860] is now STARTING
2020-01-24 22:04:10,720 INFO : org.graylog2.inputs.InputStateListener - Input [GELF TCP/5e0dd83795125a1023c2db74] is now RUNNING
2020-01-24 22:04:10,740 WARN : org.graylog2.inputs.transports.UdpTransport - receiveBufferSize (SO_RCVBUF) for input RawUDPInput{title=Cisco Meraki Security Gateway Raw/Plaintext, type=org.graylog2.inputs.raw.udp.RawUDPInput, nodeId=null} (channel [id: 0x7a5aaf31, L:/0:0:0:0:0:0:0:0%0:1025]) should be 1048576 but is 425984.
2020-01-24 22:04:10,743 WARN : org.graylog2.inputs.transports.UdpTransport - receiveBufferSize (SO_RCVBUF) for input RawUDPInput{title=Cisco Meraki Security Gateway Raw/Plaintext, type=org.graylog2.inputs.raw.udp.RawUDPInput, nodeId=null} (channel [id: 0x18983c66, L:/0:0:0:0:0:0:0:0%0:1025]) should be 1048576 but is 425984.
2020-01-24 22:04:10,743 WARN : org.graylog2.plugin.inputs.transports.AbstractTcpTransport - receiveBufferSize (SO_RCVBUF) for input GELFTCPInput{title=Cloudflare, type=org.graylog2.inputs.gelf.tcp.GELFTCPInput, nodeId=be334a85-dcdd-4794-8cbd-6c4a99555df5} (channel [id: 0x94c41b25, L:/10.0.0.67:13301]) should be 1048576 but is 425984.
2020-01-24 22:04:10,744 WARN : org.graylog2.inputs.transports.UdpTransport - receiveBufferSize (SO_RCVBUF) for input RawUDPInput{title=Cisco Meraki Security Gateway Raw/Plaintext, type=org.graylog2.inputs.raw.udp.RawUDPInput, nodeId=null} (channel [id: 0x242e5ecd, L:/0:0:0:0:0:0:0:0%0:1025]) should be 1048576 but is 425984.
2020-01-24 22:04:10,746 WARN : org.graylog2.inputs.transports.UdpTransport - receiveBufferSize (SO_RCVBUF) for input RawUDPInput{title=Cisco Meraki Security Gateway Raw/Plaintext, type=org.graylog2.inputs.raw.udp.RawUDPInput, nodeId=null} (channel [id: 0x6579e082, L:/0:0:0:0:0:0:0:0%0:1025]) should be 1048576 but is 425984.
2020-01-24 22:04:10,747 INFO : org.graylog2.inputs.InputStateListener - Input [Raw/Plaintext UDP/5e2b610095125a0f07a78860] is now RUNNING
2020-01-24 22:04:24,666 ERROR: org.graylog.plugins.auditlog.AuditLogger - Unable to write audit log entry because there is no valid license.
2020-01-24 22:04:26,269 ERROR: org.graylog.plugins.auditlog.AuditLogger - Unable to write audit log entry because there is no valid license.
2020-01-24 22:04:44,717 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
</details>

[cloudflare-logpush-content-pack.txt](https://github.com/Graylog2/graylog2-server/files/4110937/cloudflare-logpush-content-pack.txt)

![image](https://user-images.githubusercontent.com/3423655/73107919-4dbc7380-3eff-11ea-9cb7-744560f09153.png)

## Expected Behavior

The Dashboards page should load, and the pre-existing dashboards should load.

## Current Behavior

The error occurs, and all pre-existing dashboards are inaccessible.

## Steps to Reproduce (for bugs)

1. Install the content pack included above.
2. Upgrade from release 3.1.3 to 3.2.0-beta.4-SNAPSHOT+cb33786 or greater.
3. View the Dashboards page.

## Your Environment

* Graylog Version: 3.2.0-beta.4-SNAPSHOT+cb33786 (master)
* Elasticsearch Version: 6.8.3
* MongoDB Version: 3.4.2

**Comment by kmerz** [comment]
Thanks for testing @danotorrey.

I can't seem to reproduce your problem following the steps you provided.

There should be a migration fixing the problem. Can you take a look into you database if the
migration has been executed: `db.getCollection('cluster_config').find({"type": "org.graylog.plugins.views.migrations.V20190805115800_RemoveDashboardStateFromViews.MigrationCompleted"})`?

Otherwise can you try to reproduce the problem?

**Comment by danotorrey** [comment]
Thanks @kmerz! I will check if the migration completed, and will check for reproducibility.

**Comment by danotorrey** [comment]
The error was happening due to having run a master version of Graylog on the database. The error is not reproducible on a fresh 3.1.3 version upgrade. Dashboards appear to have upgraded successfully.

**Comment by chalfling** [comment]
@danotorrey How did you fix this problem?

**Comment by chalfling** [comment]
I had the same problem to upgrade 3.1.4 to 3.2.0-beta4.

My logs:
https://pastebin.com/YVsTHE4s

**Comment by danotorrey** [comment]
@chalfling In my case, I had downgraded and upgraded the same Graylog instance inadvertently before hand with a master Graylog build, which really caused some issues in my local Graylog MongoDB instance. I retested with a brand-new database and 3.1.4 installation and tested again, which was successful. This unfortunately will not help resolve the issue with your existing database. 

@kmerz Do you know how the existing database for @chalfling can be cleaned up? The specific error is:

```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "dashboard_state" (class org.graylog.plugins.views.search.views.$AutoValue_ViewDTO$Builder), not marked as ignorable (11 known properties: "state", "search_id", "properties", "summary", "title", "type", "description", "requires", "owner", "_id", "created_at"])
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@6c49c64e; pos: 1283] (through reference chain: org.graylog.plugins.views.search.views.$AutoValue_ViewDTO$Builder["dashboard_state"])
    at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:274) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:193) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3985) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2343) ~[graylog.jar:?]
    at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:80) ~[graylog.jar:?]
    at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:64) ~[graylog.jar:?]
    ... 75 more
```

**Comment by chalfling** [comment]
I tried a fresh install. My steps:

1. Install and Start MongoDB (rs.initiate)
2. Install and Start Graylog 3.1.4 (with different index set like: graylog3) and Start Graylog Server
3. Create a Content Pack with my Streams and Dashboards (from my production cluster in 3.1.4)
4. Install the Content Pack in the fresh installation.
5. Go to http://URL:9000/dashboards and see all my dashboards
6. Stop Graylog Server fresh installation and remove package
7. Install Graylog 3.2.0-beta.4 package and Start Graylog Server
8. Go to http://URL:9000/dashboards and see ONLY “Sources” Dashboard

See my fresh install logs:
https://pastebin.com/5q3q4reG

@kmerz   What did I do wrong?

**Comment by cmiscloni** [comment]
Hi all,

Same problem for me.

**Comment by kmerz** [comment]
@cmiscloni I fixed that and the line will be removed: https://github.com/Graylog2/graylog2-server/pull/7321/

**Comment by kmerz** [comment]
@cmiscloni also, as mentioned on the communtiy board: https://community.graylog.org/t/upgrade-error-from-3-1-4-to-3-2-0-b3/13561/23 the original problem of @chalfling is also addressed.

**Comment by cmiscloni** [comment]
@kmerz , the problem is still existing for me :( 
I tried to upgrade from 3.1.4 to 3.2 RC1 but I had only the default source Dashboard and a view which was migrated to Dashboard.

[http://pastebin.fr/60590](url)
