### ISSUE TITLE
Dashboard can customise with Stream name instead of Stream ID

### ISSUE THREAD

**Issue by makstock** [Graylog2/graylog2-server#8905]
Streams in the dashboard with information about total events in it, but it shows only their ID, not name. (Plz check attachment )

![image](https://user-images.githubusercontent.com/62546449/91850287-eaf03f00-ec7a-11ea-8cad-67a502bad85a.png)

## Why?

The stream name is user friendly and easy to understand when it displays on the dashboard instead of Stream ID. It should be customized according to the user requirement.

## Your Environment

* Graylog Version: 3.3.5
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Fixed in #15464.

**Comment by patrickmann** [comment]
Reopening as this is still a problem in 5.1.4 :

![image](https://github.com/Graylog2/graylog2-server/assets/12073930/b9191c11-6dca-43a2-a01e-74be3535056b)

**Comment by patrickmann** [comment]
Fixed in 5.2
